In [2]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set_style('whitegrid')

In [3]:
File = pd.ExcelFile(r"C:\Users\welcome\Desktop\EXL CASES\ROUND 2\Data.xlsx")

In [4]:
File.sheet_names

[u'Demographics',
 u'Store Mapping',
 u'Category Mapping',
 u'Ping_Information',
 u'Variable Descriptions']

In [115]:
demographics= pd.read_excel(File, 'Demographics' )
demographics.drop(['Unnamed: 0'], axis=1, inplace=True)
demographics

,Shopper_Id,ID,Age,Gender,Marital_Status,Owns_Home,Number_of_Children_under_18_years_of_age
0,Shopper_1,831b9564-99d7-3b57-a9c0-3ac1f31560d5,23,F,D,N,1
1,Shopper_2,1bd5093b-5a76-3ccc-b0d2-37695a858a95,42,F,M,N,1
2,Shopper_3,d08139f8-c50d-3472-adf8-6dcc4724164c,51,F,M,N,1
3,Shopper_4,29b285af-f631-3100-9a4e-5de09df7f974,35,F,D,N,2
4,Shopper_5,63fc3248-9900-3074-b887-c6ed6d73d0e3,42,M,S,N,0
5,Shopper_6,3fe4135c-06c1-395c-923d-f10f3552dd75,50,M,M,Y,1
6,Shopper_7,725954b6-5227-3d88-b6bf-8a6b822dd8d4,40,M,M,Y,0
7,Shopper_8,c0b4b558-84e1-3400-8f6f-18db12478292,58,M,M,Y,0
8,Shopper_9,eca4c7c4-7b92-3648-ba55-f84020ced575,36,F,M,N,2
9,Shopper_10,39a86f65-f08d-330b-8d37-57d082631adf,56,F,M,Y,1
10,Shopper_11,178732a0-709f-37de-8188-becd7d4f859f,23,F,S,N,0
11,Shopper_12,b78feb44-2b0b-3131-9935-f0802c08db3f,61,M,M,Y,0
12,Shopper_13,9cc20ae7-6b44-3c97-9f51-76789bbcf275,76,M,M,Y,2
13,Shopper_14,43eefca9-9f82-3adc-8efe-decc03100807,50,M,M,Y,2
14,Shopper_15,00d93a11-9304-345c-917a-c9be3ff4e999,25,F,M,Y,0
15,Shopper_16,e4b8f1dd-cd15-3477-8b38-f12b22c1e00d,71,M,M,Y,0
16,Shopper_17,1d367279-918a-3a87-9fe4-148b0b57fbaa,66,F,M,N,0
17,Shopper_18,96d2a6dc-0fc6-3539-a56d-3753a9cf7d95,28,F,M,Y,2
18,Shopper_19,6b98b21d-5de8-342b-a74f-2e22b17d567a,36,M,S,N,0
19,Shopper_20,0e2bda2d-9447-3963-ac56-c18b34892350,61,F,M,Y,0
20,Shopper_21,23d3ea98-d569-39f7-bf85-3a8c6804779e,39,F,D,N,1
21,Shopper_22,8a3fed0d-2b89-3c23-81b3-e574d09cff1c,63,M,M,N,0
22,Shopper_23,9595b3cd-9cca-358a-9332-beb3fc866adf,77,M,D,Y,1
23,Shopper_24,59081e1d-5dcc-3611-906e-eb9bce76f678,56,M,S,Y,0
24,Shopper_25,18dd5301-f972-3a99-b2bf-00e76e43eecd,80,F,S,Y,0
25,Shopper_26,d3b1c83b-e81d-39b5-b05f-5e56e788118a,64,F,S,Y,0
26,Shopper_27,9240bfdc-f217-3f15-8a25-56275b126406,62,M,S,Y,0
27,Shopper_28,bc811f9d-e05a-33bf-ac77-f2885989841f,46,F,M,Y,3
28,Shopper_29,8fa6c30a-ae6f-39fb-9e19-76689d8235d9,23,F,M,N,0
29,Shopper_30,92a3e8dd-449c-3e91-ab67-345909ace019,46,F,M,Y,0
...,...,...,...,...,...,...,...
537,Shopper_538,09fb9cf4-2b53-39d0-ba0d-d1bab7a4588f,24,F,S,Y,0
538,Shopper_539,3ebdd444-6192-3dbd-9731-91563c743057,63,M,M,Y,0
539,Shopper_540,0093f844-f100-3ff0-8d87-38cea990e4fd,45,M,M,N,2
540,Shopper_541,752f68b4-12e2-3d3e-a009-23fc7a7e2545,31,F,M,N,0
541,Shopper_542,32db0e93-9276-3ff3-9666-4223d7b96490,58,F,S,N,0
542,Shopper_543,2aeddf52-6dc6-39d6-becb-877e717d0e23,49,F,M,Y,1
543,Shopper_544,c7c8b32c-055f-3dd1-9bbf-b89ea7ec4c44,68,M,M,Y,0
544,Shopper_545,853923ef-9e74-3bd7-b1db-078e63bfc0ca,55,M,M,Y,0
545,Shopper_546,c4298718-00e8-349b-bc68-daa2e68f6287,61,F,M,Y,0
546,Shopper_547,dc2410cb-3c2e-3672-bf58-5cad8ebd80fd,72,M,M,Y,1
547,Shopper_548,d7cff28f-89f8-3c95-bee8-05306fe437b9,62,F,S,N,0
548,Shopper_549,4a1aeea8-bf02-31ce-ae80-054d0d71663f,56,M,S,Y,0
549,Shopper_550,e6d9272b-b5ab-33a1-b334-da4de6b2d352,68,F,S,N,0
550,Shopper_551,662e858c-a7a8-3aa0-a028-82f2cc9d7108,77,M,M,N,0
551,Shopper_552,7444d133-1a7a-33e9-b6d0-e5838ad5ec7a,42,M,S,N,0
552,Shopper_553,77d9cc00-f1b6-38dd-a887-572f663c11c4,67,M,M,N,0
553,Shopper_554,7254bebe-09b0-3359-9d5d-d55d00353e25,61,M,M,Y,0
554,Shopper_555,61f76c1f-54db-3542-99d9-bed6bb1441bd,71,M,S,Y,0
555,Shopper_556,0998e032-56c2-3579-8518-5f9260d17dec,45,F,M,Y,4
556,Shopper_557,c1757a9e-2f29-3a9d-9ffb-cbb9fd20f69b,44,F,S,N,0
557,Shopper_558,5b262605-4c8a-32ff-b917-bcf23c986cae,22,M,S,Y,0
558,Shopper_559,299782a2-5b9b-3233-836a-57fb2c7b0874,62,F,M,Y,0
559,Shopper_560,c18719bc-d3f3-3db1-9220-c9261e928ea4,49,M,M,Y,3
560,Shopper_561,432d56d7-c301-34b8-bd4a-69bd3e5e125d,27,F,S,Y,0
561,Shopper_562,3ba1d8a5-4150-3e03-a52a-ae08393f17dd,64,F,M,Y,0
562,Shopper_563,131b6acc-649d-3d5b-bd84-0385c4e360a5,27,F,S,Y,0
563,Shopper_564,24761403-2ff6-3b82-8861-1f8c91f9b8be,60,M,M,Y,1
564,Shopper_565,72b79daa-a4c1-375a-9303-f4f5580a6096,45,F,M,Y,1
565,Shopper_566,fe03a8f8-2624-3440-9ff5-45037d4afcdc,93,M,M,Y,0
566,Shopper_567,ec58077c-fc04-34a4-af31-d951098e224d,48,M,M,Y,0

In [116]:
storemapping = pd.read_excel(File, "Store Mapping")
storemapping.drop(['Unnamed: 0'], axis=1, inplace=True)
storemapping.head()

,Store_Name,Floor_name,Floor_Index,latitude,longitude
0,Jamba Juice,Concourse Level,0,37.784091,-122.406813
1,Coriander Gourmet Thai,Concourse Level,0,37.784596,-122.406210
2,NYS Collection,Concourse Level,0,37.784396,-122.406587
3,Hallmark,Concourse Level,0,37.783771,-122.407377
4,Sorabol Korean BBQ & Asian Noodles,Concourse Level,0,37.784601,-122.406328

In [117]:
categorymapping = pd.read_excel(File, "Category Mapping")
categorymapping.drop(['Unnamed: 0'], axis=1, inplace=True)
categorymapping.head()

          Store_Name Broad_Category    Fine_Category
0      Amazon Pop-Up         Retail            Misc.
1     Bespoke Events         Retail            Misc.
2  Bespoke Coworking         Retail  Specialty Store
3              Dyson         Retail            Misc.
4   Penhaligonï¿½Ûªs         Retail            Misc.

In [118]:
pinginformation = pd.read_excel(File, "Ping_Information")
pinginformation.drop(['Unnamed: 0'], axis=1, inplace=True)
pinginformation.head()

,Shopper_ID,floor,lat,lng,x,y,seenTimestamp
0,Shopper_556,Floor 4,37.661463,-122.298673,-2934.558251,-16169.722290,2016-11-22T02:16:06.000Z
1,Shopper_556,Floor 1,37.784062,-122.406943,117.262475,151.823812,2016-12-23T22:01:25.000Z
2,Shopper_556,Floor 4,37.784361,-122.406710,156.125087,171.357200,2016-11-22T01:42:28.000Z
3,Shopper_360,Concourse,37.784341,-122.406891,134.499673,167.674401,2016-10-13T18:27:38.000Z
4,Shopper_360,Floor 2,37.784017,-122.407307,94.981693,172.269243,2016-10-12T21:36:18.000Z

In [119]:
print(demographics.info(), storemapping.info(), categorymapping.info(), pinginformation.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 567 entries, 0 to 566
Data columns (total 7 columns):
Shopper_Id                                  567 non-null object
ID                                          567 non-null object
Age                                         567 non-null int64
Gender                                      567 non-null object
Marital_Status                              567 non-null object
Owns_Home                                   567 non-null object
Number_of_Children_under_18_years_of_age    567 non-null int64
dtypes: int64(2), object(5)
memory usage: 31.1+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166 entries, 0 to 165
Data columns (total 5 columns):
Store_Name     166 non-null object
Floor_name     166 non-null object
Floor_Index    166 non-null int64
latitude       166 non-null float64
longitude      166 non-null float64
dtypes: float64(2), int64(1), object(2)
memory usage: 6.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 154 entries, 0 to 153
Data columns (total 3 columns):
Store_Name        154 non-null object
Broad_Category    154 non-null object
Fine_Category     154 non-null object
dtypes: object(3)
memory usage: 3.7+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 107635 entries, 0 to 107634
Data columns (total 7 columns):
Shopper_ID       107635 non-null object
floor            107635 non-null object
lat              107635 non-null float64
lng              107635 non-null float64
x                107635 non-null float64
y                107635 non-null float64
seenTimestamp    107635 non-null object
dtypes: float64(4), object(3)
memory usage: 5.7+ MB
(None, None, None, None)

In [120]:
storemap = storemapping.drop(['Floor_name'], axis=1)
storemap.head()

                           Store_Name  Floor_Index   latitude   longitude
0                         Jamba Juice            0  37.784091 -122.406813
1              Coriander Gourmet Thai            0  37.784596 -122.406210
2                      NYS Collection            0  37.784396 -122.406587
3                            Hallmark            0  37.783771 -122.407377
4  Sorabol Korean BBQ & Asian Noodles            0  37.784601 -122.406328

In [121]:
pinginfo=pinginformation.drop(['x', 'y', 'seenTimestamp'], axis=1)
pinginfo.head()

    Shopper_ID      floor        lat         lng
0  Shopper_556    Floor 4  37.661463 -122.298673
1  Shopper_556    Floor 1  37.784062 -122.406943
2  Shopper_556    Floor 4  37.784361 -122.406710
3  Shopper_360  Concourse  37.784341 -122.406891
4  Shopper_360    Floor 2  37.784017 -122.407307

In [122]:
floors= sorted(pinginfo['floor'].unique())
floors

[u'Concourse', u'Floor 1', u'Floor 2', u'Floor 3', u'Floor 4']

In [123]:
floor_mapping= dict(zip(floors, range(0, len(floors) + 1)))
floor_mapping

{u'Concourse': 0, u'Floor 1': 1, u'Floor 2': 2, u'Floor 3': 3, u'Floor 4': 4}

In [124]:
pinginfo['Floor_Index']= pinginfo['floor'].map(floor_mapping).astype(int)
pinginfo.head()

    Shopper_ID      floor        lat         lng  Floor_Index
0  Shopper_556    Floor 4  37.661463 -122.298673            4
1  Shopper_556    Floor 1  37.784062 -122.406943            1
2  Shopper_556    Floor 4  37.784361 -122.406710            4
3  Shopper_360  Concourse  37.784341 -122.406891            0
4  Shopper_360    Floor 2  37.784017 -122.407307            2

In [125]:
pinginfo.drop(['floor'], axis=1, inplace= True)
pinginfo['latitude']= pinginfo['lat']
pinginfo['longitude']= pinginfo['lng']
pinginfo.head()

    Shopper_ID        lat         lng  Floor_Index   latitude   longitude
0  Shopper_556  37.661463 -122.298673            4  37.661463 -122.298673
1  Shopper_556  37.784062 -122.406943            1  37.784062 -122.406943
2  Shopper_556  37.784361 -122.406710            4  37.784361 -122.406710
3  Shopper_360  37.784341 -122.406891            0  37.784341 -122.406891
4  Shopper_360  37.784017 -122.407307            2  37.784017 -122.407307

In [126]:
pinginfo.drop(['lat', 'lng'], axis=1, inplace= True)
pinginfo.head()

    Shopper_ID  Floor_Index   latitude   longitude
0  Shopper_556            4  37.661463 -122.298673
1  Shopper_556            1  37.784062 -122.406943
2  Shopper_556            4  37.784361 -122.406710
3  Shopper_360            0  37.784341 -122.406891
4  Shopper_360            2  37.784017 -122.407307

In [127]:
#training:
X = storemap.drop(['Store_Name'],axis=1).as_matrix().astype(np.float)
X

array([[   0.      ,   37.784091, -122.406813],
       [   0.      ,   37.784596, -122.40621 ],
       [   0.      ,   37.784396, -122.406587],
       [   0.      ,   37.783771, -122.407377],
       [   0.      ,   37.784601, -122.406328],
       [   0.      ,   37.784534, -122.406025],
       [   0.      ,   37.783944, -122.407537],
       [   0.      ,   37.784447, -122.406224],
       [   0.      ,   37.784161, -122.4069  ],
       [   0.      ,   37.784808, -122.406501],
       [   0.      ,   37.784569, -122.406141],
       [   0.      ,   37.78467 , -122.406679],
       [   0.      ,   37.784126, -122.407061],
       [   0.      ,   37.784159, -122.40635 ],
       [   0.      ,   37.783959, -122.40691 ],
       [   0.      ,   37.784411, -122.406709],
       [   0.      ,   37.784511, -122.405956],
       [   0.      ,   37.784071, -122.406885],
       [   0.      ,   37.784591, -122.406782],
       [   0.      ,   37.783778, -122.407161],
       [   0.      ,   37.784053, -122.407307],
       [   0.      ,   37.783893, -122.407389],
       [   0.      ,   37.784222, -122.406978],
       [   0.      ,   37.783953, -122.407318],
       [   0.      ,   37.784505, -122.406555],
       [   0.      ,   37.783767, -122.40707 ],
       [   0.      ,   37.784106, -122.407189],
       [   0.      ,   37.784292, -122.40601 ],
       [   0.      ,   37.784449, -122.406665],
       [   0.      ,   37.784353, -122.406773],
       [   0.      ,   37.784294, -122.406164],
       [   0.      ,   37.78432 , -122.406195],
       [   0.      ,   37.783944, -122.407175],
       [   0.      ,   37.783831, -122.406941],
       [   0.      ,   37.784312, -122.405822],
       [   0.      ,   37.783887, -122.405783],
       [   0.      ,   37.784208, -122.40743 ],
       [   0.      ,   37.784505, -122.406399],
       [   0.      ,   37.784625, -122.406417],
       [   0.      ,   37.784123, -122.40695 ],
       [   0.      ,   37.78413 , -122.407374],
       [   0.      ,   37.784037, -122.406937],
       [   0.      ,   37.784457, -122.406819],
       [   0.      ,   37.784415, -122.405846],
       [   0.      ,   37.784116, -122.407124],
       [   0.      ,   37.784157, -122.405925],
       [   0.      ,   37.784094, -122.407625],
       [   0.      ,   37.783791, -122.406984],
       [   1.      ,   37.78379 , -122.40747 ],
       [   1.      ,   37.784615, -122.406332],
       [   1.      ,   37.78402 , -122.405965],
       [   1.      ,   37.784179, -122.406865],
       [   1.      ,   37.784142, -122.40704 ],
       [   1.      ,   37.784453, -122.406443],
       [   1.      ,   37.784033, -122.406896],
       [   1.      ,   37.784267, -122.406579],
       [   1.      ,   37.784296, -122.406519],
       [   1.      ,   37.784464, -122.406181],
       [   1.      ,   37.784195, -122.40696 ],
       [   1.      ,   37.784221, -122.406652],
       [   1.      ,   37.784776, -122.406643],
       [   1.      ,   37.784527, -122.406296],
       [   1.      ,   37.78367 , -122.407313],
       [   1.      ,   37.783731, -122.407122],
       [   1.      ,   37.783976, -122.406906],
       [   1.      ,   37.784613, -122.406467],
       [   1.      ,   37.78398 , -122.407454],
       [   1.      ,   37.784714, -122.406476],
       [   1.      ,   37.78409 , -122.406835],
       [   1.      ,   37.784503, -122.406813],
       [   1.      ,   37.784112, -122.406949],
       [   1.      ,   37.784884, -122.406486],
       [   1.      ,   37.78461 , -122.406886],
       [   1.      ,   37.784466, -122.406961],
       [   1.      ,   37.78447 , -122.40676 ],
       [   1.      ,   37.78373 , -122.407061],
       [   1.      ,   37.783909, -122.407393],
       [   1.      ,   37.78381 , -122.407336],
       [   1.      ,   37.783864, -122.406836],
       [   1.      ,   37.784188, -122.407159],
       [   1.      ,   37.783827, -122.407024],
       [   1.      ,   37.784047, -122.407035],
       [   1.      ,   37.784397, -122.406148],
       [   1.      ,   37.784185, -122.406379],
       [   1.      ,   37.784396, -122.406726],
       [   2.      ,   37.784579, -122.406476],
       [   2.      ,   37.783744, -122.407323],
       [   2.      ,   37.784515, -122.406218],
       [   2.      ,   37.784024, -122.407272],
       [   2.      ,   37.784139, -122.407183],
       [   2.      ,   37.784341, -122.406785],
       [   2.      ,   37.784559, -122.40627 ],
       [   2.      ,   37.784136, -122.405805],
       [   2.      ,   37.784705, -122.406568],
       [   2.      ,   37.784142, -122.40742 ],
       [   2.      ,   37.784267, -122.406528],
       [   2.      ,   37.784046, -122.406884],
       [   2.      ,   37.784252, -122.406942],
       [   2.      ,   37.784387, -122.406732],
       [   2.      ,   37.783739, -122.407271],
       [   2.      ,   37.783745, -122.407149],
       [   2.      ,   37.784385, -122.406276],
       [   2.      ,   37.784195, -122.407081],
       [   2.      ,   37.784433, -122.40608 ],
       [   2.      ,   37.784031, -122.406181],
       [   2.      ,   37.783852, -122.405805],
       [   2.      ,   37.783931, -122.406086],
       [   2.      ,   37.784484, -122.406502],
       [   2.      ,   37.783724, -122.406893],
       [   2.      ,   37.784555, -122.406814],
       [   2.      ,   37.783832, -122.407021],
       [   2.      ,   37.783954, -122.407507],
       [   2.      ,   37.784185, -122.406432],
       [   2.      ,   37.783864, -122.406924],
       [   2.      ,   37.783946, -122.406796],
       [   2.      ,   37.784316, -122.40656 ],
       [   2.      ,   37.784172, -122.406733],
       [   2.      ,   37.784271, -122.406619],
       [   2.      ,   37.784286, -122.406001],
       [   3.      ,   37.784042, -122.406901],
       [   3.      ,   37.783629, -122.407154],
       [   3.      ,   37.783741, -122.406902],
       [   3.      ,   37.784628, -122.406187],
       [   3.      ,   37.78435 , -122.406064],
       [   3.      ,   37.784105, -122.406326],
       [   3.      ,   37.784615, -122.406862],
       [   3.      ,   37.784428, -122.406643],
       [   3.      ,   37.784447, -122.406809],
       [   3.      ,   37.783986, -122.406922],
       [   3.      ,   37.783839, -122.406836],
       [   3.      ,   37.783812, -122.406021],
       [   3.      ,   37.784133, -122.407419],
       [   3.      ,   37.783752, -122.407371],
       [   3.      ,   37.78429 , -122.406561],
       [   3.      ,   37.783737, -122.407253],
       [   3.      ,   37.78424 , -122.406455],
       [   3.      ,   37.784101, -122.406854],
       [   3.      ,   37.783871, -122.407073],
       [   3.      ,   37.784153, -122.405871],
       [   3.      ,   37.783745, -122.405601],
       [   3.      ,   37.784191, -122.407111],
       [   3.      ,   37.784267, -122.405933],
       [   3.      ,   37.784386, -122.406589],
       [   3.      ,   37.78454 , -122.406132],
       [   3.      ,   37.783912, -122.407474],
       [   3.      ,   37.784663, -122.406313],
       [   3.      ,   37.784135, -122.406406],
       [   3.      ,   37.783957, -122.406249],
       [   3.      ,   37.783814, -122.407399],
       [   3.      ,   37.784197, -122.40698 ],
       [   3.      ,   37.784701, -122.406758],
       [   3.      ,   37.78436 , -122.406786],
       [   4.      ,   37.78442 , -122.406832],
       [   4.      ,   37.784702, -122.406248],
       [   4.      ,   37.784206, -122.406528],
       [   4.      ,   37.784178, -122.405776],
       [   4.      ,   37.783859, -122.40635 ],
       [   4.      ,   37.784539, -122.406081],
       [   4.      ,   37.78382 , -122.407311],
       [   4.      ,   37.783802, -122.405736],
       [   5.      ,   37.784076, -122.407307],
       [   5.      ,   37.78389 , -122.405736],
       [   5.      ,   37.784204, -122.406574],
       [   6.      ,   37.78409 , -122.407309],
       [   7.      ,   37.784073, -122.407289],
       [   8.      ,   37.784087, -122.407307]])

In [2]:
#pd.DataFrame?

In [128]:
'''elements = np.array(X)
elements'''

'elements = np.array(X)\nelements'

In [129]:
'''mean = np.mean(elements, axis=0)
sd = np.std(elements, axis=0)'''

'mean = np.mean(elements, axis=0)\nsd = np.std(elements, axis=0)'

In [130]:
'''final_list = [x for x in X if (np.all(x) > mean - 2 * sd)]
final_list = [x for x in final_list if (np.all(x) < mean + 2 * sd)]
'''

'final_list = [x for x in X if (np.all(x) > mean - 2 * sd)]\nfinal_list = [x for x in final_list if (np.all(x) < mean + 2 * sd)]\n'

In [131]:
#convert into matrix having mean= 0 and std dev= 1
from sklearn import preprocessing
scaler = preprocessing.StandardScaler()
X = scaler.fit_transform(X)
X

array([[-1.08827864e+00, -3.44149111e-01, -2.21927721e-01],
       [-1.08827864e+00,  1.40158609e+00,  1.04342435e+00],
       [-1.08827864e+00,  7.10205813e-01,  2.52317003e-01],
       [-1.08827864e+00, -1.45035756e+00, -1.40544110e+00],
       [-1.08827864e+00,  1.41887060e+00,  7.95809851e-01],
       [-1.08827864e+00,  1.18725820e+00,  1.43163353e+00],
       [-1.08827864e+00, -8.52313615e-01, -1.74118958e+00],
       [-1.08827864e+00,  8.86507784e-01,  1.01404636e+00],
       [-1.08827864e+00, -1.02166013e-01, -4.04490955e-01],
       [-1.08827864e+00,  2.13444919e+00,  4.32781810e-01],
       [-1.08827864e+00,  1.30824975e+00,  1.18821588e+00],
       [-1.08827864e+00,  1.65739679e+00,  5.92616288e-02],
       [-1.08827864e+00, -2.23157562e-01, -7.42337861e-01],
       [-1.08827864e+00, -1.09079816e-01,  7.49644435e-01],
       [-1.08827864e+00, -8.00460094e-01, -4.25475235e-01],
       [-1.08827864e+00,  7.62059334e-01, -3.69121068e-03],
       [-1.08827864e+00,  1.10774947e+00,  1.57642506e+00],
       [-1.08827864e+00, -4.13287138e-01, -3.73014536e-01],
       [-1.08827864e+00,  1.38430158e+00, -1.56876453e-01],
       [-1.08827864e+00, -1.42615925e+00, -9.52180659e-01],
       [-1.08827864e+00, -4.75511363e-01, -1.25855114e+00],
       [-1.08827864e+00, -1.02861559e+00, -1.43062224e+00],
       [-1.08827864e+00,  1.08704971e-01, -5.68168338e-01],
       [-1.08827864e+00, -8.21201502e-01, -1.28163385e+00],
       [-1.08827864e+00,  1.08700806e+00,  3.19466699e-01],
       [-1.08827864e+00, -1.46418516e+00, -7.61223712e-01],
       [-1.08827864e+00, -2.92295590e-01, -1.01093664e+00],
       [-1.08827864e+00,  3.50688069e-01,  1.46310995e+00],
       [-1.08827864e+00,  8.93421587e-01,  8.86396206e-02],
       [-1.08827864e+00,  5.61559053e-01, -1.37990602e-01],
       [-1.08827864e+00,  3.57601871e-01,  1.13995204e+00],
       [-1.08827864e+00,  4.47481308e-01,  1.07490077e+00],
       [-1.08827864e+00, -8.52313615e-01, -9.81558651e-01],
       [-1.08827864e+00, -1.24294347e+00, -4.90526503e-01],
       [-1.08827864e+00,  4.19826096e-01,  1.85761441e+00],
       [-1.08827864e+00, -1.04935699e+00,  1.93945310e+00],
       [-1.08827864e+00,  6.03083520e-02, -1.51665779e+00],
       [-1.08827864e+00,  1.08700806e+00,  6.46821464e-01],
       [-1.08827864e+00,  1.50183623e+00,  6.09049760e-01],
       [-1.08827864e+00, -2.33528266e-01, -5.09412354e-01],
       [-1.08827864e+00, -2.09329956e-01, -1.39914582e+00],
       [-1.08827864e+00, -5.30821786e-01, -4.82132791e-01],
       [-1.08827864e+00,  9.21076798e-01, -2.34518289e-01],
       [-1.08827864e+00,  7.75886940e-01,  1.80725214e+00],
       [-1.08827864e+00, -2.57726576e-01, -8.74538823e-01],
       [-1.08827864e+00, -1.15993619e-01,  1.64147633e+00],
       [-1.08827864e+00, -3.33778406e-01, -1.92585124e+00],
       [-1.08827864e+00, -1.38121953e+00, -5.80758906e-01],
       [-4.24108586e-01, -1.38467643e+00, -1.60059491e+00],
       [-4.24108586e-01,  1.46726722e+00,  7.87416139e-01],
       [-4.24108586e-01, -5.89589109e-01,  1.55753921e+00],
       [-4.24108586e-01, -3.99417883e-02, -3.31045976e-01],
       [-4.24108586e-01, -1.67847140e-01, -6.98270873e-01],
       [-4.24108586e-01,  9.07249192e-01,  5.54490633e-01],
       [-4.24108586e-01, -5.44649391e-01, -3.96097243e-01],
       [-4.24108586e-01,  2.64265534e-01,  2.69104427e-01],
       [-4.24108586e-01,  3.64515674e-01,  3.95010106e-01],
       [-4.24108586e-01,  9.45275108e-01,  1.10427876e+00],
       [-4.24108586e-01,  1.53686339e-02, -5.30396634e-01],
       [-4.24108586e-01,  1.05248070e-01,  1.15919184e-01],
       [-4.24108586e-01,  2.02382834e+00,  1.34805036e-01],
       [-4.24108586e-01,  1.16305990e+00,  8.62959546e-01],
       [-4.24108586e-01, -1.79950460e+00, -1.27114171e+00],
       [-4.24108586e-01, -1.58863361e+00, -8.70341967e-01],
       [-4.24108586e-01, -7.41692770e-01, -4.17081523e-01],
       [-4.24108586e-01,  1.46035341e+00,  5.04128361e-01],
       [-4.24108586e-01, -7.27865165e-01, -1.56702006e+00],
       [-4.24108586e-01,  1.80950046e+00,  4.85242509e-01],
       [-4.24108586e-01, -3.47606012e-01, -2.68093136e-01],
       [-4.24108586e-01,  1.08009426e+00, -2.21927721e-01],
       [-4.24108586e-01, -2.71554181e-01, -5.07313926e-01],
       [-4.24108586e-01,  2.39717369e+00,  4.64258229e-01],
       [-4.24108586e-01,  1.44998271e+00, -3.75112964e-01],
       [-4.24108586e-01,  9.52188910e-01, -5.32495062e-01],
       [-4.24108586e-01,  9.66016516e-01, -1.10711038e-01],
       [-4.24108586e-01, -1.59209051e+00, -7.42337861e-01],
       [-4.24108586e-01, -9.73305163e-01, -1.43901595e+00],
       [-4.24108586e-01, -1.31553840e+00, -1.31940556e+00],
       [-4.24108586e-01, -1.12886573e+00, -2.70191564e-01],
       [-4.24108586e-01, -8.82967582e-03, -9.47983803e-01],
       [-4.24108586e-01, -1.25677108e+00, -6.64696025e-01],
       [-4.24108586e-01, -4.96252772e-01, -6.87778733e-01],
       [-4.24108586e-01,  7.13662715e-01,  1.17352689e+00],
       [-4.24108586e-01, -1.92003800e-02,  6.88790024e-01],
       [-4.24108586e-01,  7.10205813e-01, -3.93644864e-02],
       [ 2.40061464e-01,  1.34281877e+00,  4.85242509e-01],
       [ 2.40061464e-01, -1.54369389e+00, -1.29212599e+00],
       [ 2.40061464e-01,  1.12157708e+00,  1.02663693e+00],
       [ 2.40061464e-01, -5.75761504e-01, -1.18510616e+00],
       [ 2.40061464e-01, -1.78217844e-01, -9.98346074e-01],
       [ 2.40061464e-01,  5.20076237e-01, -1.63171737e-01],
       [ 2.40061464e-01,  1.27368074e+00,  9.17518674e-01],
       [ 2.40061464e-01, -1.88588548e-01,  1.89328769e+00],
       [ 2.40061464e-01,  1.77838834e+00,  2.92187135e-01],
       [ 2.40061464e-01, -1.67847140e-01, -1.49567351e+00],
       [ 2.40061464e-01,  2.64265534e-01,  3.76124254e-01],
       [ 2.40061464e-01, -4.99709673e-01, -3.70916108e-01],
       [ 2.40061464e-01,  2.12412013e-01, -4.92624931e-01],
       [ 2.40061464e-01,  6.79093701e-01, -5.19550543e-02],
       [ 2.40061464e-01, -1.56097840e+00, -1.18300774e+00],
       [ 2.40061464e-01, -1.54023699e+00, -9.26999523e-01],
       [ 2.40061464e-01,  6.72179898e-01,  9.04928106e-01],
       [ 2.40061464e-01,  1.53686339e-02, -7.84306420e-01],
       [ 2.40061464e-01,  8.38111165e-01,  1.31621999e+00],
       [ 2.40061464e-01, -5.51563194e-01,  1.10427876e+00],
       [ 2.40061464e-01, -1.17034854e+00,  1.89328769e+00],
       [ 2.40061464e-01, -8.97253333e-01,  1.30362942e+00],
       [ 2.40061464e-01,  1.01441314e+00,  4.30683382e-01],
       [ 2.40061464e-01, -1.61283192e+00, -3.89801959e-01],
       [ 2.40061464e-01,  1.25985313e+00, -2.24026149e-01],
       [ 2.40061464e-01, -1.23948657e+00, -6.58400741e-01],
       [ 2.40061464e-01, -8.17744601e-01, -1.67823674e+00],
       [ 2.40061464e-01, -1.92003800e-02,  5.77573341e-01],
       [ 2.40061464e-01, -1.12886573e+00, -4.54853227e-01],
       [ 2.40061464e-01, -8.45399812e-01, -1.86254445e-01],
       [ 2.40061464e-01,  4.33653702e-01,  3.08974559e-01],
       [ 2.40061464e-01, -6.41400981e-02, -5.40534823e-02],
       [ 2.40061464e-01,  2.78093139e-01,  1.85167308e-01],
       [ 2.40061464e-01,  3.29946660e-01,  1.48199580e+00],
       [ 9.04231513e-01, -5.13537279e-01, -4.06589383e-01],
       [ 9.04231513e-01, -1.94123755e+00, -9.37491663e-01],
       [ 9.04231513e-01, -1.55406460e+00, -4.08687811e-01],
       [ 9.04231513e-01,  1.51220694e+00,  1.09168820e+00],
       [ 9.04231513e-01,  5.51188349e-01,  1.34979484e+00],
       [ 9.04231513e-01, -2.95752491e-01,  8.00006707e-01],
       [ 9.04231513e-01,  1.46726722e+00, -3.24750692e-01],
       [ 9.04231513e-01,  8.20826658e-01,  1.34805036e-01],
       [ 9.04231513e-01,  8.86507784e-01, -2.13534009e-01],
       [ 9.04231513e-01, -7.07123756e-01, -4.50656371e-01],
       [ 9.04231513e-01, -1.21528826e+00, -2.70191564e-01],
       [ 9.04231513e-01, -1.30862460e+00,  1.44002724e+00],
       [ 9.04231513e-01, -1.98959252e-01, -1.49357508e+00],
       [ 9.04231513e-01, -1.51603868e+00, -1.39285054e+00],
       [ 9.04231513e-01,  3.43774266e-01,  3.06876131e-01],
       [ 9.04231513e-01, -1.56789220e+00, -1.14523603e+00],
       [ 9.04231513e-01,  1.70929196e-01,  5.29309497e-01],
       [ 9.04231513e-01, -3.09580097e-01, -3.07963268e-01],
       [ 9.04231513e-01, -1.10466742e+00, -7.67518996e-01],
       [ 9.04231513e-01, -1.29821224e-01,  1.75479144e+00],
       [ 9.04231513e-01, -1.54023699e+00,  2.32136699e+00],
       [ 9.04231513e-01,  1.54102834e-03, -8.47259260e-01],
       [ 9.04231513e-01,  2.64265534e-01,  1.62468890e+00],
       [ 9.04231513e-01,  6.75636799e-01,  2.48120147e-01],
       [ 9.04231513e-01,  1.20799961e+00,  1.20710174e+00],
       [ 9.04231513e-01, -9.62934459e-01, -1.60898862e+00],
       [ 9.04231513e-01,  1.63319848e+00,  8.27286270e-01],
       [ 9.04231513e-01, -1.92045449e-01,  6.32132468e-01],
       [ 9.04231513e-01, -8.07373897e-01,  9.61585661e-01],
       [ 9.04231513e-01, -1.30171080e+00, -1.45160652e+00],
       [ 9.04231513e-01,  2.22824367e-02, -5.72365194e-01],
       [ 9.04231513e-01,  1.76456074e+00, -1.06514182e-01],
       [ 9.04231513e-01,  5.85757363e-01, -1.65270165e-01],
       [ 1.56840156e+00,  7.93171447e-01, -2.61797853e-01],
       [ 1.56840156e+00,  1.76801764e+00,  9.63684089e-01],
       [ 1.56840156e+00,  5.33945492e-02,  3.76124254e-01],
       [ 1.56840156e+00, -4.33986897e-02,  1.95414210e+00],
       [ 1.56840156e+00, -1.14615023e+00,  7.49644435e-01],
       [ 1.56840156e+00,  1.20454271e+00,  1.31412156e+00],
       [ 1.56840156e+00, -1.28096939e+00, -1.26694486e+00],
       [ 1.56840156e+00, -1.34319361e+00,  2.03807922e+00],
       [ 2.23257161e+00, -3.96002631e-01, -1.25855114e+00],
       [ 2.23257161e+00, -1.03898629e+00,  2.03807922e+00],
       [ 2.23257161e+00,  4.64807464e-02,  2.79596567e-01],
       [ 2.89674166e+00, -3.47606012e-01, -1.26274800e+00],
       [ 3.56091171e+00, -4.06373336e-01, -1.22077944e+00],
       [ 4.22508176e+00, -3.57976716e-01, -1.25855114e+00]])

In [132]:
y = storemap['Store_Name'].as_matrix().astype(np.object)
y

array([u'Jamba Juice', u'Coriander Gourmet Thai', u'NYS Collection',
       u'Hallmark', u'Sorabol Korean BBQ & Asian Noodles', u'Pasta Moto',
       u'Abercrombie & Fitch', u'Fire of Brazil', u'ProActiv Solutions ',
       u'Corner W', u'Buckhorn Grill', u'Cako Bakery',
       u"Claire's Boutique", u'Bristol Farms', u'PacSun', u'DAVIDsTEA',
       u'Andale Mexican Restaurant', u'Sunglass Hut ',
       u"Peet's Coffee & Tea", u'Panda Express', u'GNC', u'New Era',
       u'LEGO', u'Mrs. Fields', u"Beard Papa's Cream Puffs",
       u'Ajisen Ramen', u'Shoe Palace ', u'Loving Hut Vegan Cuisine ',
       u'Ghirardelli Ice Cream and Chocolate Shop ',
       u'Marbles: The Brain Store', u'Caffe Central', u'Pressed Juicery',
       u'Cafe Bellini', u'Sarku Japan', u'Kichi Grill', u"Bloomingdale's",
       u'Warriors Team Store', u'Lobster Me',
       u'Amoura Cafe Fresh Mediterranean', u"Wetzel's Pretzels",
       u'Shoe Wiz', u'Haagen Dazs', u'Sur La Table',
       u"Charley's Grilled Subs", u'Champs Sports',
       u'San Francisco Soup Company', u'Starbucks', u'Chipotle', u'Razer',
       u'Madewell', u"Bloomingdale's", u'Swatch', u"Kiehl's",
       u'Amazon Pop-Up', u'Janie And Jack', u'The Art of Shaving',
       u'RED Valentino', u'Burberry', u'Swarovski',
       u'Brighton Collectibles', u'Michael Kors', u'Karen Millen',
       u'Aritzia', u'Tumi', u'Kate Spade New York',
       u'Penhaligon\xef\xbf\xbd\xdb\xaas', u'Abercrombie & Fitch',
       u'Tory Burch ', u"L'Occitane en Provence", u'Rolex',
       u'Sunglass Hut', u'Timberland', u'Tourneau', u'Adidas',
       u'Superdry ', u'Origins', u'Club Monaco Men',
       u'Currency Exchange International ', u'Club Monaco Women',
       u'American Eagle Outfitters', u'Nordstrom E-Bar', u"Kiehl's",
       u'Tiffany & Co.', u'BOSS', u'Michael Kors Men',
       u'lululemon athletica', u'Coach', u'bareMinerals',
       u'Forever Flawless ', u'OAK+FORT', u"Auntie Anne's Pretzels",
       u'Max & Co.', u'Onassis', u'Zara', u'bebe', u'ECCO',
       u'Lady Foot Locker', u'Cotton On', u'Pandora', u'The Body Shop',
       u'Express', u'T-Mobile', u'Brookstone', u'BCBGMAXAZRIA',
       u'H&M Man', u"Bloomingdale's", u'49ers Team Store',
       u'Studio Manhattan', u"Francesca's Collection ", u'Adidas',
       u'Dyson', u'Hollister Co.', u'Microsoft', u'Samsonite', u'GUESS ',
       u'Aveda', u'Camper', u'Yoppi Frozen Yogurt ', u'J.Crew',
       u'The Walking Company', u'Express', u'Papyrus',
       u'San Francisco Luggage Co.', u'Banana Republic', u'Vera Bradley',
       u'Eddie Bauer', u'Godiva Chocolatier', u'SF Sports', u'Aldo',
       u'House of Hoops by Foot Locker', u'abercrombie kids',
       u"Victoria's Secret", u'Perfumania', u'Kay Jewelers',
       u'Amiri Salon', u'Clarks', u'Lids', u'iPlay n Talk',
       u'Go! Toys and Games', u"Bloomingdale's", u'Fossil', u'Vans',
       u'Eyebrow Plus', u'True Religion Jeans', u'Finish Line',
       u'Lucky Brand Jeans', u'Bath & Body Works', u'H&M', u'Teavana',
       u'Steve Madden', u'Forever Flawless', u'Solstice', u'TAP 415',
       u'Optica', u'M.Y. China', u'Bespoke Coworking', u'Bespoke Events',
       u'Bose', u'Nordstrom', u"Bloomingdale's", u'Nordstrom',
       u'Century San Francisco Centre 9', u'Burke Williams Day Spa',
       u'Nordstrom', u'Nordstrom', u'Nordstrom'], dtype=object)

In [133]:
#CV:
import numpy as np
from sklearn.model_selection import train_test_split

from sklearn import cross_validation
from sklearn import tree
from sklearn import svm
from sklearn import ensemble
from sklearn import neighbors
from sklearn import linear_model
from sklearn import metrics

In [134]:
def stratified_cv(X, y, clf_class, shuffle=True, n_folds=2, **kwargs):
    stratified_k_fold = cross_validation.StratifiedKFold(y, n_folds=n_folds, shuffle=shuffle)
    y_pred = y.copy()
    for ii, jj in stratified_k_fold:
        X_train, X_test = X[ii], X[jj]
        y_train = y[ii]
        clf = clf_class(**kwargs)
        clf.fit(X_train,y_train)
        y_pred[jj] = clf.predict(X_test)
    return y_pred

In [136]:
print('Passive Aggressive Classifier: {:.2f}'.format(metrics.accuracy_score(y, stratified_cv(X, y, linear_model.PassiveAggressiveClassifier))))
print('Gradient Boosting Classifier:  {:.2f}'.format(metrics.accuracy_score(y, stratified_cv(X, y, ensemble.GradientBoostingClassifier))))
print('Support vector machine(SVM):   {:.2f}'.format(metrics.accuracy_score(y, stratified_cv(X, y, svm.SVC))))
print('Random Forest Classifier:      {:.2f}'.format(metrics.accuracy_score(y, stratified_cv(X, y, ensemble.RandomForestClassifier))))
print('K Nearest Neighbor Classifier: {:.2f}'.format(metrics.accuracy_score(y, stratified_cv(X, y, neighbors.KNeighborsClassifier))))
print('Logistic Regression:           {:.2f}'.format(metrics.accuracy_score(y, stratified_cv(X, y, linear_model.LogisticRegression))))

Passive Aggressive Classifier: 0.01
Gradient Boosting Classifier:  0.04
Support vector machine(SVM):   0.04
Random Forest Classifier:      0.05
K Nearest Neighbor Classifier: 0.07
Logistic Regression:           0.07

In [137]:
#FITTING TO LOGREG:
X_test = pinginfo.drop(['Shopper_ID'], axis=1).as_matrix().astype(np.float)
X_test

array([[   4.        ,   37.66146302, -122.2986728 ],
       [   1.        ,   37.78406211, -122.4069432 ],
       [   4.        ,   37.78436125, -122.4067095 ],
       ...,
       [   2.        ,   36.0179502 , -116.704627  ],
       [   1.        ,   37.78404745, -122.4069997 ],
       [   0.        ,   37.78407819, -122.4070869 ]])

In [139]:
scaler = preprocessing.StandardScaler()
test_data = scaler.fit_transform(X_test)
test_data

array([[ 1.83464372,  0.36209925, -0.40275272],
       [-0.32798594,  0.42248019, -0.41922354],
       [ 1.83464372,  0.42262752, -0.41918799],
       ...,
       [ 0.39289061, -0.44734271,  0.44825139],
       [-0.32798594,  0.42247297, -0.41923214],
       [-1.04886249,  0.42248811, -0.4192454 ]])

In [144]:
from sklearn import linear_model
clf= linear_model.LogisticRegression(penalty = 'l2', solver ='lbfgs', C=100000, random_state =0)
train_features = X

train_target = y

# Fit the model to our training data
clf = clf.fit(train_features, train_target)
score = clf.score(train_features, train_target)
"Mean accuracy: {0}".format(score)F

'Mean accuracy: 0.849397590361'

In [141]:
'''from sklearn.svm import SVC

clf = svm.SVC(kernel='rbf', gamma=100, C=1)
clf.fit(X, y)


# Training data features
train_features = X

# target column values
train_target = y

# Fit the model to our training data
clf = clf.fit(train_features, train_target)
score = clf.score(train_features, train_target)
"Mean accuracy of SVM: {0}".format(score)'''

'Mean accuracy of SVM: 1.0'

In [145]:
pred_y= clf.predict(test_data)

In [146]:
pinginfo['Store_Name'] = pred_y
pinginfo.head(100)

     Shopper_ID  Floor_Index   latitude   longitude        Store_Name
0   Shopper_556            4  37.661463 -122.298673           TAP 415
1   Shopper_556            1  37.784062 -122.406943           Kiehl's
2   Shopper_556            4  37.784361 -122.406710           TAP 415
3   Shopper_360            0  37.784341 -122.406891           Kiehl's
4   Shopper_360            2  37.784017 -122.407307         Cotton On
5   Shopper_420            4  37.661624 -122.298459           TAP 415
6   Shopper_420            1  37.783856 -122.407092           Kiehl's
7   Shopper_245            2  37.783970 -122.407194         Cotton On
8   Shopper_334            2  37.783828 -122.406986         Cotton On
9   Shopper_205            1  37.784219 -122.406896           Kiehl's
10  Shopper_205            0  37.784638 -122.406411           Kiehl's
11  Shopper_530            1  35.085149 -113.663734  49ers Team Store
12  Shopper_530            0  36.541271 -118.435462       Jamba Juice
13  Shopper_359            0  37.783961 -122.407034           Kiehl's
14  Shopper_189            0  35.239976 -114.220990    Bloomingdale's
15  Shopper_189            0  37.784049 -122.407055           Kiehl's
16  Shopper_189            0  37.784084 -122.407044           Kiehl's
17  Shopper_481            2  35.265054 -114.246672           H&M Man
18  Shopper_155            4  37.784287 -122.406954           TAP 415
19  Shopper_155            1  36.980523 -119.811229           Kiehl's
20  Shopper_155            4  37.759561 -122.385293           TAP 415
21  Shopper_287            0  37.656648 -122.006913           Kiehl's
22  Shopper_536            2  34.031987 -110.253652    Bloomingdale's
23  Shopper_344            2  37.784028 -122.407106         Cotton On
24   Shopper_41            2  33.504061 -108.734063    Bloomingdale's
25   Shopper_41            3  37.783814 -122.407127          Solstice
26  Shopper_122            4  36.066776 -116.842850        M.Y. China
27   Shopper_51            0  37.720868 -122.343518           Kiehl's
28   Shopper_51            1  35.265134 -114.246611  49ers Team Store
29   Shopper_68            1  37.783840 -122.407236           Kiehl's
..          ...          ...        ...         ...               ...
70  Shopper_180            2  36.468473 -118.174922         Microsoft
71  Shopper_449            1  37.783913 -122.407134           Kiehl's
72  Shopper_449            4  37.722828 -122.352689           TAP 415
73  Shopper_561            1  36.879668 -119.478708           Kiehl's
74  Shopper_475            3  37.783922 -122.407186          Solstice
75  Shopper_557            1  37.784189 -122.406847           Kiehl's
76   Shopper_98            1  37.784015 -122.407044           Kiehl's
77   Shopper_98            0  37.784161 -122.406898           Kiehl's
78   Shopper_98            3  37.784055 -122.407036          Solstice
79  Shopper_268            3  37.783936 -122.407100          Solstice
80  Shopper_268            4  29.082109  -94.277709    Bloomingdale's
81  Shopper_550            0  37.784015 -122.407177           Kiehl's
82  Shopper_550            1  37.714475 -122.182005           Kiehl's
83  Shopper_550            0  37.783980 -122.407110           Kiehl's
84   Shopper_27            0  37.710393 -122.342140           Kiehl's
85   Shopper_27            0  37.784047 -122.407153           Kiehl's
86  Shopper_212            4  28.338228  -91.804871    Bloomingdale's
87  Shopper_212            2  33.544888 -108.770188    Bloomingdale's
88  Shopper_212            0  34.315595 -111.249673    Bloomingdale's
89  Shopper_405            0  37.784146 -122.407033           Kiehl's
90  Shopper_405            2  37.784104 -122.407331         Cotton On
91  Shopper_405            4  35.756871 -115.930030        M.Y. China
92   Shopper_60            4  37.784251 -122.406806           TAP 415
93    Shopper_8            1  37.783982 -122.406909           Kiehl's
94    Shopper_8            1  37.783863 -122.407156           Kiehl's
95    Shopper_8            0  37.784020 -122.407079           Kiehl's
96  Shopper_213            1  37.783982 -122.406909           Kiehl's
97   Shopper_59            2  37.783816 -122.407319         Cotton On
98   Shopper_35            1  37.783982 -122.406909           Kiehl's
99  Shopper_197            1  37.784137 -122.407002           Kiehl's

[100 rows x 5 columns]

In [147]:
#pinginfo.sort_index(axis=0, level=None, ascending=True, inplace=True, kind='quicksort', na_position='last', sort_remaining=True, by='Shopper_ID')

In [148]:
#shoppers= sorted(pinginfo['Shopper_ID'].unique(),key=lambda x: int(x[8:]))

In [33]:
#shopper_list = pinginfo['Shopper_ID'].as_matrix().astype(np.object)

In [34]:
#shopper_list

In [35]:
'''lists=[]
a='_'
for shopper in shopper_list:
    new= shopper.split(a)
    lists.append(int(new[1]))
foobar=[str(x) for x in sorted(lists)]
    '''

"lists=[]\na='_'\nfor shopper in shopper_list:\n    new= shopper.split(a)\n    lists.append(int(new[1]))\nfoobar=[str(x) for x in sorted(lists)]\n    "

In [36]:
#foobar

In [149]:
pinginfo.head(100)

     Shopper_ID  Floor_Index   latitude   longitude        Store_Name
0   Shopper_556            4  37.661463 -122.298673           TAP 415
1   Shopper_556            1  37.784062 -122.406943           Kiehl's
2   Shopper_556            4  37.784361 -122.406710           TAP 415
3   Shopper_360            0  37.784341 -122.406891           Kiehl's
4   Shopper_360            2  37.784017 -122.407307         Cotton On
5   Shopper_420            4  37.661624 -122.298459           TAP 415
6   Shopper_420            1  37.783856 -122.407092           Kiehl's
7   Shopper_245            2  37.783970 -122.407194         Cotton On
8   Shopper_334            2  37.783828 -122.406986         Cotton On
9   Shopper_205            1  37.784219 -122.406896           Kiehl's
10  Shopper_205            0  37.784638 -122.406411           Kiehl's
11  Shopper_530            1  35.085149 -113.663734  49ers Team Store
12  Shopper_530            0  36.541271 -118.435462       Jamba Juice
13  Shopper_359            0  37.783961 -122.407034           Kiehl's
14  Shopper_189            0  35.239976 -114.220990    Bloomingdale's
15  Shopper_189            0  37.784049 -122.407055           Kiehl's
16  Shopper_189            0  37.784084 -122.407044           Kiehl's
17  Shopper_481            2  35.265054 -114.246672           H&M Man
18  Shopper_155            4  37.784287 -122.406954           TAP 415
19  Shopper_155            1  36.980523 -119.811229           Kiehl's
20  Shopper_155            4  37.759561 -122.385293           TAP 415
21  Shopper_287            0  37.656648 -122.006913           Kiehl's
22  Shopper_536            2  34.031987 -110.253652    Bloomingdale's
23  Shopper_344            2  37.784028 -122.407106         Cotton On
24   Shopper_41            2  33.504061 -108.734063    Bloomingdale's
25   Shopper_41            3  37.783814 -122.407127          Solstice
26  Shopper_122            4  36.066776 -116.842850        M.Y. China
27   Shopper_51            0  37.720868 -122.343518           Kiehl's
28   Shopper_51            1  35.265134 -114.246611  49ers Team Store
29   Shopper_68            1  37.783840 -122.407236           Kiehl's
..          ...          ...        ...         ...               ...
70  Shopper_180            2  36.468473 -118.174922         Microsoft
71  Shopper_449            1  37.783913 -122.407134           Kiehl's
72  Shopper_449            4  37.722828 -122.352689           TAP 415
73  Shopper_561            1  36.879668 -119.478708           Kiehl's
74  Shopper_475            3  37.783922 -122.407186          Solstice
75  Shopper_557            1  37.784189 -122.406847           Kiehl's
76   Shopper_98            1  37.784015 -122.407044           Kiehl's
77   Shopper_98            0  37.784161 -122.406898           Kiehl's
78   Shopper_98            3  37.784055 -122.407036          Solstice
79  Shopper_268            3  37.783936 -122.407100          Solstice
80  Shopper_268            4  29.082109  -94.277709    Bloomingdale's
81  Shopper_550            0  37.784015 -122.407177           Kiehl's
82  Shopper_550            1  37.714475 -122.182005           Kiehl's
83  Shopper_550            0  37.783980 -122.407110           Kiehl's
84   Shopper_27            0  37.710393 -122.342140           Kiehl's
85   Shopper_27            0  37.784047 -122.407153           Kiehl's
86  Shopper_212            4  28.338228  -91.804871    Bloomingdale's
87  Shopper_212            2  33.544888 -108.770188    Bloomingdale's
88  Shopper_212            0  34.315595 -111.249673    Bloomingdale's
89  Shopper_405            0  37.784146 -122.407033           Kiehl's
90  Shopper_405            2  37.784104 -122.407331         Cotton On
91  Shopper_405            4  35.756871 -115.930030        M.Y. China
92   Shopper_60            4  37.784251 -122.406806           TAP 415
93    Shopper_8            1  37.783982 -122.406909           Kiehl's
94    Shopper_8            1  37.783863 -122.407156           Kiehl's
95    Shopper_8            0  37.784020 -122.407079           Kiehl's
96  Shopper_213            1  37.783982 -122.406909           Kiehl's
97   Shopper_59            2  37.783816 -122.407319         Cotton On
98   Shopper_35            1  37.783982 -122.406909           Kiehl's
99  Shopper_197            1  37.784137 -122.407002           Kiehl's

[100 rows x 5 columns]

In [38]:
#new_ping= pinginfo.groupby(['Shopper_ID', 'Store_Name','Floor_Index', 'latitude', 'longitude',' Store_Name'])

In [154]:
visiting_info = pinginfo.groupby(['Shopper_ID', 'Store_Name']).describe()

In [163]:
visiting_info.drop(['latitude', 'longitude'], axis=1, inplace=True)
visiting_info.head()

                            Floor_Index                                     \
                                  count      mean       std  min  25%  50%
Shopper_ID Store_Name
Shopper_1  49ers Team Store         7.0  1.571429  0.534522  1.0  1.0  2.0
           BOSS                     3.0  1.000000  0.000000  1.0  1.0  1.0
           Bloomingdale's          67.0  1.119403  1.135146  0.0  0.0  1.0
           Bristol Farms            5.0  0.000000  0.000000  0.0  0.0  0.0
           Cotton On               12.0  2.000000  0.000000  2.0  2.0  2.0


                             75%  max
Shopper_ID Store_Name
Shopper_1  49ers Team Store  2.0  2.0
           BOSS              1.0  1.0
           Bloomingdale's    2.0  4.0
           Bristol Farms     0.0  0.0
           Cotton On         2.0  2.0

In [164]:
#visiting_info.to_csv(r"C:\Users\welcome\Desktop\visitinginfo.csv")

In [165]:
visitinginfo = pd.read_csv(r"C:\Users\welcome\Desktop\visitinginfo.csv")
visitinginfo

,Shopper_ID,Store_Name,count,mean,std,min,25%,50%,75%,max
0,Shopper_1,49ers Team Store,7,1.571429,0.534522,1,1.00,2.0,2.00,2
1,Shopper_1,BOSS,3,1.000000,0.000000,1,1.00,1.0,1.00,1
2,Shopper_1,Bloomingdale's,67,1.119403,1.135146,0,0.00,1.0,2.00,4
3,Shopper_1,Bristol Farms,5,0.000000,0.000000,0,0.00,0.0,0.00,0
4,Shopper_1,Cotton On,12,2.000000,0.000000,2,2.00,2.0,2.00,2
5,Shopper_1,H&M,11,3.000000,0.000000,3,3.00,3.0,3.00,3
6,Shopper_1,H&M Man,5,2.000000,0.000000,2,2.00,2.0,2.00,2
7,Shopper_1,Kiehl's,47,0.404255,0.577083,0,0.00,0.0,1.00,2
8,Shopper_1,M.Y. China,2,4.000000,0.000000,4,4.00,4.0,4.00,4
9,Shopper_1,Solstice,18,3.000000,0.000000,3,3.00,3.0,3.00,3
10,Shopper_1,TAP 415,8,4.000000,0.000000,4,4.00,4.0,4.00,4
11,Shopper_1,Vera Bradley,2,3.000000,0.000000,3,3.00,3.0,3.00,3
12,Shopper_1,abercrombie kids,2,3.000000,0.000000,3,3.00,3.0,3.00,3
13,Shopper_10,49ers Team Store,6,1.166667,0.408248,1,1.00,1.0,1.00,2
14,Shopper_10,BOSS,1,1.000000,NaN,1,1.00,1.0,1.00,1
15,Shopper_10,Bespoke Events,4,4.000000,0.000000,4,4.00,4.0,4.00,4
16,Shopper_10,Bloomingdale's,4,1.500000,1.732051,0,0.75,1.0,1.75,4
17,Shopper_10,Bristol Farms,1,0.000000,NaN,0,0.00,0.0,0.00,0
18,Shopper_10,Cotton On,3,2.000000,0.000000,2,2.00,2.0,2.00,2
19,Shopper_10,H&M Man,1,2.000000,NaN,2,2.00,2.0,2.00,2
20,Shopper_10,Jamba Juice,1,0.000000,NaN,0,0.00,0.0,0.00,0
21,Shopper_10,Kiehl's,76,0.671053,0.640586,0,0.00,1.0,1.00,2
22,Shopper_10,M.Y. China,13,4.000000,0.000000,4,4.00,4.0,4.00,4
23,Shopper_10,Microsoft,1,2.000000,NaN,2,2.00,2.0,2.00,2
24,Shopper_10,Solstice,1,4.000000,NaN,4,4.00,4.0,4.00,4
25,Shopper_10,TAP 415,75,4.000000,0.000000,4,4.00,4.0,4.00,4
26,Shopper_100,49ers Team Store,5,1.200000,0.447214,1,1.00,1.0,1.00,2
27,Shopper_100,BOSS,7,1.000000,0.000000,1,1.00,1.0,1.00,1
28,Shopper_100,Bath & Body Works,2,3.000000,0.000000,3,3.00,3.0,3.00,3
29,Shopper_100,Bespoke Events,3,4.000000,0.000000,4,4.00,4.0,4.00,4
...,...,...,...,...,...,...,...,...,...,...
6147,Shopper_97,Solstice,19,3.000000,0.000000,3,3.00,3.0,3.00,3
6148,Shopper_97,TAP 415,9,4.000000,0.000000,4,4.00,4.0,4.00,4
6149,Shopper_97,Vera Bradley,1,3.000000,NaN,3,3.00,3.0,3.00,3
6150,Shopper_98,49ers Team Store,1,1.000000,NaN,1,1.00,1.0,1.00,1
6151,Shopper_98,Bloomingdale's,3,0.666667,0.577350,0,0.50,1.0,1.00,1
6152,Shopper_98,Bristol Farms,3,0.000000,0.000000,0,0.00,0.0,0.00,0
6153,Shopper_98,Cotton On,44,2.000000,0.000000,2,2.00,2.0,2.00,2
6154,Shopper_98,H&M Man,1,2.000000,NaN,2,2.00,2.0,2.00,2
6155,Shopper_98,Kiehl's,115,0.426087,0.496671,0,0.00,0.0,1.00,1
6156,Shopper_98,M.Y. China,1,4.000000,NaN,4,4.00,4.0,4.00,4
6157,Shopper_98,Solstice,21,3.000000,0.000000,3,3.00,3.0,3.00,3
6158,Shopper_98,TAP 415,1,4.000000,NaN,4,4.00,4.0,4.00,4
6159,Shopper_99,49ers Team Store,3,1.000000,0.000000,1,1.00,1.0,1.00,1
6160,Shopper_99,BOSS,6,1.000000,0.000000,1,1.00,1.0,1.00,1
6161,Shopper_99,Bath & Body Works,2,3.000000,0.000000,3,3.00,3.0,3.00,3
6162,Shopper_99,Bespoke Events,11,4.000000,0.000000,4,4.00,4.0,4.00,4
6163,Shopper_99,Bloomingdale's,6,1.166667,0.752773,0,1.00,1.0,1.75,2
6164,Shopper_99,Bristol Farms,4,0.000000,0.000000,0,0.00,0.0,0.00,0
6165,Shopper_99,Camper,5,2.000000,0.000000,2,2.00,2.0,2.00,2
6166,Shopper_99,Cotton On,20,2.000000,0.000000,2,2.00,2.0,2.00,2
6167,Shopper_99,H&M,1,3.000000,NaN,3,3.00,3.0,3.00,3
6168,Shopper_99,H&M Man,5,2.000000,0.000000,2,2.00,2.0,2.00,2
6169,Shopper_99,Jamba Juice,2,0.000000,0.000000,0,0.00,0.0,0.00,0
6170,Shopper_99,Kiehl's,92,0.510870,0.620077,0,0.00,0.0,1.00,2
6171,Shopper_99,M.Y. China,2,4.000000,0.000000,4,4.00,4.0,4.00,4
6172,Shopper_99,Microsoft,4,2.000000,0.000000,2,2.00,2.0,2.00,2
6173,Shopper_99,Solstice,8,3.000000,0.000000,3,3.00,3.0,3.00,3
6174,Shopper_99,TAP 415,17,4.000000,0.000000,4,4.00,4.0,4.00,4
6175,Shopper_99,Vera Bradley,1,4.000000,NaN,4,4.00,4.0,4.00,4
6176,Shopper_99,abercrombie kids,1,3.000000,NaN,3,3.00,3.0,3.00,3

In [166]:
from scipy import stats
df_freq = pinginfo.groupby(by='Shopper_ID').Store_Name.apply(stats.mode)
df_freq

Shopper_ID
Shopper_1      ([Bloomingdale's], [67])
Shopper_10            ([Kiehl's], [76])
Shopper_100           ([Kiehl's], [99])
Shopper_101           ([Kiehl's], [99])
Shopper_102          ([TAP 415], [125])
Shopper_103           ([Kiehl's], [72])
Shopper_104          ([Kiehl's], [118])
Shopper_105          ([Kiehl's], [110])
Shopper_106          ([Kiehl's], [123])
Shopper_107           ([Kiehl's], [96])
Shopper_108          ([Kiehl's], [166])
Shopper_109           ([Kiehl's], [72])
Shopper_11           ([Kiehl's], [107])
Shopper_110           ([Kiehl's], [72])
Shopper_111          ([Kiehl's], [103])
Shopper_112          ([Kiehl's], [105])
Shopper_113          ([Kiehl's], [137])
Shopper_114           ([TAP 415], [89])
Shopper_115           ([Kiehl's], [56])
Shopper_116          ([TAP 415], [166])
Shopper_117          ([Kiehl's], [154])
Shopper_118          ([Kiehl's], [106])
Shopper_119          ([Kiehl's], [144])
Shopper_12            ([Kiehl's], [72])
Shopper_120          ([Kiehl's], [111])
Shopper_121           ([Kiehl's], [80])
Shopper_122           ([Kiehl's], [72])
Shopper_123          ([Kiehl's], [139])
Shopper_124          ([Kiehl's], [126])
Shopper_125           ([Kiehl's], [70])
                         ...
Shopper_72            ([Kiehl's], [84])
Shopper_73            ([Kiehl's], [85])
Shopper_74           ([Kiehl's], [120])
Shopper_75           ([Kiehl's], [109])
Shopper_76           ([Kiehl's], [181])
Shopper_77            ([Kiehl's], [64])
Shopper_78            ([Kiehl's], [61])
Shopper_79            ([Kiehl's], [73])
Shopper_8             ([Kiehl's], [95])
Shopper_80            ([Kiehl's], [90])
Shopper_81            ([Kiehl's], [96])
Shopper_82            ([Kiehl's], [73])
Shopper_83           ([Kiehl's], [105])
Shopper_84            ([TAP 415], [85])
Shopper_85           ([Kiehl's], [141])
Shopper_86            ([Kiehl's], [76])
Shopper_87            ([Kiehl's], [62])
Shopper_88            ([Kiehl's], [77])
Shopper_89           ([Kiehl's], [138])
Shopper_9            ([Kiehl's], [119])
Shopper_90           ([Kiehl's], [106])
Shopper_91           ([Kiehl's], [128])
Shopper_92            ([Kiehl's], [98])
Shopper_93            ([Kiehl's], [52])
Shopper_94            ([Kiehl's], [93])
Shopper_95           ([Kiehl's], [121])
Shopper_96            ([Kiehl's], [91])
Shopper_97     ([Bloomingdale's], [59])
Shopper_98           ([Kiehl's], [115])
Shopper_99            ([Kiehl's], [92])
Name: Store_Name, Length: 567, dtype: object

In [167]:
df_freq= df_freq.to_frame()
df_freq.iloc[1,:]

Store_Name    ([Kiehl's], [76])
Name: Shopper_10, dtype: object

In [168]:
mostvisitedshoplist= []
for shop in df_freq['Store_Name']:
    mostvisitedshoplist.append(shop[0][0])
mostvisitedshop_array= np.array(mostvisitedshoplist)
mostvisitedshop_array.astype(object)

array([u"Bloomingdale's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u'TAP 415',
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u'TAP 415', u"Kiehl's", u'TAP 415',
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u'TAP 415', u"Bloomingdale's",
       u"Bloomingdale's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u'Cotton On', u"Kiehl's", u"Kiehl's", u'TAP 415',
       u"Bloomingdale's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u'TAP 415', u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u'TAP 415', u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u'Cotton On', u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Bloomingdale's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u'TAP 415', u"Kiehl's", u'TAP 415',
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Bloomingdale's",
       u"Bloomingdale's", u"Kiehl's", u"Bloomingdale's", u"Kiehl's",
       u"Kiehl's", u'TAP 415', u'TAP 415', u"Kiehl's", u"Kiehl's",
       u"Bloomingdale's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u'TAP 415',
       u"Kiehl's", u"Kiehl's", u'TAP 415', u"Kiehl's", u'TAP 415',
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u'TAP 415', u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u'TAP 415', u"Kiehl's", u'TAP 415', u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u'Cotton On', u"Bloomingdale's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Bloomingdale's",
       u"Kiehl's", u"Kiehl's", u'Cotton On', u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u'Cotton On', u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u'TAP 415', u"Bloomingdale's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u'Cotton On', u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u'TAP 415',
       u"Bloomingdale's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u'TAP 415', u"Kiehl's", u'TAP 415', u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u'Cotton On',
       u'TAP 415', u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u'TAP 415', u"Kiehl's", u"Kiehl's", u'TAP 415', u"Kiehl's",
       u'Cotton On', u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u'Cotton On', u"Kiehl's",
       u"Kiehl's", u'Solstice', u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u'TAP 415', u'Solstice', u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Bloomingdale's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u'Solstice', u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Bloomingdale's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u'Solstice', u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u'Cotton On',
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u'Cotton On', u'TAP 415', u"Kiehl's", u"Kiehl's", u'TAP 415',
       u"Kiehl's", u'Cotton On', u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u'TAP 415', u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Bloomingdale's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u'TAP 415', u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Bloomingdale's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u'Solstice',
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u'Cotton On', u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u'TAP 415', u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u'Solstice', u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u'TAP 415',
       u"Kiehl's", u'TAP 415', u'TAP 415', u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u'TAP 415', u"Kiehl's",
       u'TAP 415', u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u'TAP 415', u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Bloomingdale's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u'TAP 415', u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u'Solstice', u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Bloomingdale's", u"Kiehl's",
       u'Solstice', u"Kiehl's", u'TAP 415', u'Cotton On', u"Kiehl's",
       u"Kiehl's", u'TAP 415', u"Kiehl's", u"Kiehl's", u'TAP 415',
       u"Kiehl's", u"Kiehl's", u'TAP 415', u"Kiehl's", u"Kiehl's",
       u"Bloomingdale's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Bloomingdale's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Bloomingdale's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u'TAP 415', u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u'TAP 415', u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's",
       u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Kiehl's", u"Bloomingdale's",
       u"Kiehl's", u"Kiehl's"], dtype=object)

In [169]:
df_freq['New_Store']= mostvisitedshop_array
df_freq.head()

                           Store_Name       New_Store
Shopper_ID
Shopper_1    ([Bloomingdale's], [67])  Bloomingdale's
Shopper_10          ([Kiehl's], [76])         Kiehl's
Shopper_100         ([Kiehl's], [99])         Kiehl's
Shopper_101         ([Kiehl's], [99])         Kiehl's
Shopper_102        ([TAP 415], [125])         TAP 415

In [170]:
df_freq.to_csv(r"C:\Users\welcome\Desktop\exl__round1_.csv")

In [171]:
pinginfo.head()

    Shopper_ID  Floor_Index   latitude   longitude Store_Name
0  Shopper_556            4  37.661463 -122.298673    TAP 415
1  Shopper_556            1  37.784062 -122.406943    Kiehl's
2  Shopper_556            4  37.784361 -122.406710    TAP 415
3  Shopper_360            0  37.784341 -122.406891    Kiehl's
4  Shopper_360            2  37.784017 -122.407307  Cotton On

In [172]:
categorymapping.head()

          Store_Name Broad_Category    Fine_Category
0      Amazon Pop-Up         Retail            Misc.
1     Bespoke Events         Retail            Misc.
2  Bespoke Coworking         Retail  Specialty Store
3              Dyson         Retail            Misc.
4   Penhaligonï¿½Ûªs         Retail            Misc.

In [173]:
for stores, category in zip(categorymapping['Store_Name'], categorymapping['Fine_Category']):
    store_and_category_mapping = dict(zip(categorymapping['Store_Name'], categorymapping['Fine_Category']))

In [174]:
store_and_category_mapping

{u'49ers Team Store': u'Sports Stores',
 u'Abercrombie & Fitch': u'Apparel And Accessories',
 u'Adidas': u'Apparel And Accessories',
 u'Ajisen Ramen': u'Qsr Restaurants',
 u'Aldo': u'Shoe Stores',
 u'Amazon Pop-Up': u'Misc.',
 u'American Eagle Outfitters': u'Apparel And Accessories',
 u'Amiri Salon': u'Furniture And Decor',
 u'Amoura Cafe Fresh Mediterranean': u'Qsr Restaurants',
 u'Andale Mexican Restaurant': u'Qsr Restaurants',
 u'Aritzia': u'Apparel And Accessories',
 u"Auntie Anne's Pretzels": u'Qsr Restaurants',
 u'Aveda': u'Furniture And Decor',
 u'BCBGMAXAZRIA': u'Apparel And Accessories',
 u'BOSS': u'Apparel And Accessories',
 u'Banana Republic': u'Apparel And Accessories',
 u'Bath & Body Works': u'Furniture And Decor',
 u"Beard Papa's Cream Puffs": u'Qsr Restaurants',
 u'Bespoke Coworking': u'Specialty Store',
 u'Bespoke Events': u'Misc.',
 u"Bloomingdale's": u'Department Stores',
 u'Bose': u'Electronics Stores',
 u'Brighton Collectibles': u'Apparel And Accessories',
 u'Bristol Farms': u'Casual Restaurants',
 u'Brookstone': u'Department Stores',
 u'Buckhorn Grill': u'Qsr Restaurants',
 u'Burberry': u'Apparel And Accessories',
 u'Burke Williams Day Spa': u'Misc.',
 u'Cafe Bellini': u'Qsr Restaurants',
 u'Caffe Central': u'Qsr Restaurants',
 u'Cako Bakery': u'Qsr Restaurants',
 u'Camper': u'Shoe Stores',
 u'Century San Francisco Centre 9': u'Misc.',
 u'Champs Sports': u'Sports Stores',
 u"Charley's Grilled Subs": u'Qsr Restaurants',
 u'Chipotle': u'Qsr Restaurants',
 u"Claire's Boutique": u'Apparel And Accessories',
 u'Clarks': u'Shoe Stores',
 u'Club Monaco Men': u'Apparel And Accessories',
 u'Club Monaco Women': u'Apparel And Accessories',
 u'Coach': u'Apparel And Accessories',
 u'Coriander Gourmet Thai': u'Qsr Restaurants',
 u'Corner W': u'Shoe Stores',
 u'Cotton On': u'Apparel And Accessories',
 u'Currency Exchange International ': u'Misc.',
 u'DAVIDsTEA': u'Qsr Restaurants',
 u'Dyson': u'Misc.',
 u'ECCO': u'Shoe Stores',
 u'Eddie Bauer': u'Apparel And Accessories',
 u'Express': u'Apparel And Accessories',
 u'Eyebrow Plus': u'Furniture And Decor',
 u'Finish Line': u'Apparel And Accessories',
 u'Fire of Brazil': u'Qsr Restaurants',
 u'Forever Flawless': u'Furniture And Decor',
 u'Forever Flawless ': u'Furniture And Decor',
 u'Fossil': u'Apparel And Accessories',
 u"Francesca's Collection ": u'Apparel And Accessories',
 u'GNC': u'Furniture And Decor',
 u'GUESS ': u'Apparel And Accessories',
 u'Ghirardelli Ice Cream and Chocolate Shop ': u'Qsr Restaurants',
 u'Go! Toys and Games': u'Toy Stores',
 u'Godiva Chocolatier': u'Qsr Restaurants',
 u'H&M': u'Apparel And Accessories',
 u'H&M Man': u'Apparel And Accessories',
 u'Haagen Dazs': u'Qsr Restaurants',
 u'Hallmark': u'Office Supply Stores',
 u'Hollister Co.': u'Apparel And Accessories',
 u'House of Hoops by Foot Locker': u'Sports Stores',
 u'J.Crew': u'Apparel And Accessories',
 u'Jamba Juice': u'Qsr Restaurants',
 u'Janie And Jack': u'Apparel And Accessories',
 u'Karen Millen': u'Apparel And Accessories',
 u'Kate Spade New York': u'Apparel And Accessories',
 u'Kay Jewelers': u'Misc.',
 u'Kichi Grill': u'Qsr Restaurants',
 u"Kiehl's": u'Furniture And Decor',
 u"L'Occitane en Provence": u'Furniture And Decor',
 u'LEGO': u'Toy Stores',
 u'Lady Foot Locker': u'Sports Stores',
 u'Lids': u'Apparel and Accessories',
 u'Lobster Me': u'Qsr Restaurants',
 u'Loving Hut Vegan Cuisine ': u'Qsr Restaurants',
 u'Lucky Brand Jeans': u'Apparel And Accessories',
 u'M.Y. China': u'Qsr Restaurants',
 u'Madewell': u'Apparel And Accessories',
 u'Marbles: The Brain Store': u'Toy Stores',
 u'Max & Co.': u'Apparel And Accessories',
 u'Michael Kors': u'Apparel And Accessories',
 u'Michael Kors Men': u'Apparel And Accessories',
 u'Microsoft': u'Electronics Stores',
 u'Mrs. Fields': u'Qsr Restaurants',
 u'NYS Collection': u'Apparel And Accessories',
 u'New Era': u'Sports Stores',
 u'Nordstrom': u'Department Stores',
 u'Nordstrom E-Bar': u'Qsr Restaurants',
 u'OAK+FORT': u'Apparel And Accessories',
 u'Onassis': u'Furniture And Decor',
 u'Optica': u'Furniture And Decor',
 u'Origins': u'Furniture And Decor',
 u'PacSun': u'Apparel And Accessories',
 u'Panda Express': u'Qsr Restaurants',
 u'Pandora': u'Misc.',
 u'Papyrus': u'Office Supply Stores',
 u'Pasta Moto': u'Qsr Restaurants',
 u"Peet's Coffee & Tea": u'Qsr Restaurants',
 u'Penhaligon\xef\xbf\xbd\xdb\xaas': u'Misc.',
 u'Perfumania': u'Furniture And Decor',
 u'Pressed Juicery': u'Qsr Restaurants',
 u'ProActiv Solutions ': u'Misc.',
 u'RED Valentino': u'Apparel And Accessories',
 u'Razer': u'Specialty Store',
 u'Rolex': u'Misc.',
 u'SF Sports': u'Apparel And Accessories',
 u'Samsonite': u'Apparel and Accessories',
 u'San Francisco Luggage Co.': u'Apparel and Accessories',
 u'San Francisco Soup Company': u'Qsr Restaurants',
 u'Sarku Japan': u'Qsr Restaurants',
 u'Shoe Palace ': u'Shoe Stores',
 u'Shoe Wiz': u'Misc.',
 u'Solstice': u'Apparel And Accessories',
 u'Sorabol Korean BBQ & Asian Noodles': u'Qsr Restaurants',
 u'Starbucks': u'Qsr Restaurants',
 u'Steve Madden': u'Shoe Stores',
 u'Studio Manhattan': u'Apparel and Accessories',
 u'Sunglass Hut': u'Apparel And Accessories',
 u'Sunglass Hut ': u'Apparel And Accessories',
 u'Superdry ': u'Apparel And Accessories',
 u'Sur La Table': u'Furniture And Decor',
 u'Swarovski': u'Apparel and Accessories',
 u'Swatch': u'Misc.',
 u'T-Mobile': u'Cellular Phone Stores',
 u'TAP 415': u'Qsr Restaurants',
 u'Teavana': u'Qsr Restaurants',
 u'The Art of Shaving': u'Furniture And Decor',
 u'The Body Shop': u'Furniture And Decor',
 u'The Walking Company': u'Shoe Stores',
 u'Tiffany & Co.': u'Misc.',
 u'Timberland': u'Apparel And Accessories',
 u'Tory Burch ': u'Apparel And Accessories',
 u'Tourneau': u'Misc.',
 u'True Religion Jeans': u'Apparel And Accessories',
 u'Tumi': u'Apparel and Accessories',
 u'Vans': u'Shoe Stores',
 u'Vera Bradley': u'Apparel And Accessories',
 u"Victoria's Secret": u'Apparel And Accessories',
 u'Warriors Team Store': u'Sports Stores',
 u"Wetzel's Pretzels": u'Qsr Restaurants',
 u'Yoppi Frozen Yogurt ': u'Qsr Restaurants',
 u'Zara': u'Apparel And Accessories',
 u'abercrombie kids': u'Apparel And Accessories',
 u'bareMinerals': u'Furniture And Decor',
 u'bebe': u'Apparel And Accessories',
 u'iPlay n Talk': u'Electronics Stores',
 u'lululemon athletica': u'Apparel and Accessories'}

In [175]:
storemap['Store_Category'] = storemap['Store_Name'].map(store_and_category_mapping).astype(object)
storemap.head()

,Store_Name,Floor_Index,latitude,longitude,Store_Category
0,Jamba Juice,0,37.784091,-122.406813,Qsr Restaurants
1,Coriander Gourmet Thai,0,37.784596,-122.406210,Qsr Restaurants
2,NYS Collection,0,37.784396,-122.406587,Apparel And Accessories
3,Hallmark,0,37.783771,-122.407377,Office Supply Stores
4,Sorabol Korean BBQ & Asian Noodles,0,37.784601,-122.406328,Qsr Restaurants

In [176]:
Store_Categories= sorted(storemap['Store_Category'].unique())
Store_Categories_mapping = dict(zip(Store_Categories, range(0, len(Store_Categories) + 1)))
Store_Categories_mapping

{u'Apparel And Accessories': 0,
 u'Apparel and Accessories': 1,
 u'Casual Restaurants': 2,
 u'Cellular Phone Stores': 3,
 u'Department Stores': 4,
 u'Electronics Stores': 5,
 u'Furniture And Decor': 6,
 u'Misc.': 7,
 u'Office Supply Stores': 8,
 u'Qsr Restaurants': 9,
 u'Shoe Stores': 10,
 u'Specialty Store': 11,
 u'Sports Stores': 12,
 u'Toy Stores': 13}

In [177]:
storemap['Category_Index'] = storemap['Store_Category'].map(Store_Categories_mapping).astype(int)
storemap.head()

,Store_Name,Floor_Index,latitude,longitude,Store_Category,Category_Index
0,Jamba Juice,0,37.784091,-122.406813,Qsr Restaurants,9
1,Coriander Gourmet Thai,0,37.784596,-122.406210,Qsr Restaurants,9
2,NYS Collection,0,37.784396,-122.406587,Apparel And Accessories,0
3,Hallmark,0,37.783771,-122.407377,Office Supply Stores,8
4,Sorabol Korean BBQ & Asian Noodles,0,37.784601,-122.406328,Qsr Restaurants,9

In [178]:
X2 = storemap.drop(['Store_Name', 'Store_Category' ,'Category_Index'],axis=1).as_matrix().astype(np.float)
X2

array([[   0.      ,   37.784091, -122.406813],
       [   0.      ,   37.784596, -122.40621 ],
       [   0.      ,   37.784396, -122.406587],
       [   0.      ,   37.783771, -122.407377],
       [   0.      ,   37.784601, -122.406328],
       [   0.      ,   37.784534, -122.406025],
       [   0.      ,   37.783944, -122.407537],
       [   0.      ,   37.784447, -122.406224],
       [   0.      ,   37.784161, -122.4069  ],
       [   0.      ,   37.784808, -122.406501],
       [   0.      ,   37.784569, -122.406141],
       [   0.      ,   37.78467 , -122.406679],
       [   0.      ,   37.784126, -122.407061],
       [   0.      ,   37.784159, -122.40635 ],
       [   0.      ,   37.783959, -122.40691 ],
       [   0.      ,   37.784411, -122.406709],
       [   0.      ,   37.784511, -122.405956],
       [   0.      ,   37.784071, -122.406885],
       [   0.      ,   37.784591, -122.406782],
       [   0.      ,   37.783778, -122.407161],
       [   0.      ,   37.784053, -122.407307],
       [   0.      ,   37.783893, -122.407389],
       [   0.      ,   37.784222, -122.406978],
       [   0.      ,   37.783953, -122.407318],
       [   0.      ,   37.784505, -122.406555],
       [   0.      ,   37.783767, -122.40707 ],
       [   0.      ,   37.784106, -122.407189],
       [   0.      ,   37.784292, -122.40601 ],
       [   0.      ,   37.784449, -122.406665],
       [   0.      ,   37.784353, -122.406773],
       [   0.      ,   37.784294, -122.406164],
       [   0.      ,   37.78432 , -122.406195],
       [   0.      ,   37.783944, -122.407175],
       [   0.      ,   37.783831, -122.406941],
       [   0.      ,   37.784312, -122.405822],
       [   0.      ,   37.783887, -122.405783],
       [   0.      ,   37.784208, -122.40743 ],
       [   0.      ,   37.784505, -122.406399],
       [   0.      ,   37.784625, -122.406417],
       [   0.      ,   37.784123, -122.40695 ],
       [   0.      ,   37.78413 , -122.407374],
       [   0.      ,   37.784037, -122.406937],
       [   0.      ,   37.784457, -122.406819],
       [   0.      ,   37.784415, -122.405846],
       [   0.      ,   37.784116, -122.407124],
       [   0.      ,   37.784157, -122.405925],
       [   0.      ,   37.784094, -122.407625],
       [   0.      ,   37.783791, -122.406984],
       [   1.      ,   37.78379 , -122.40747 ],
       [   1.      ,   37.784615, -122.406332],
       [   1.      ,   37.78402 , -122.405965],
       [   1.      ,   37.784179, -122.406865],
       [   1.      ,   37.784142, -122.40704 ],
       [   1.      ,   37.784453, -122.406443],
       [   1.      ,   37.784033, -122.406896],
       [   1.      ,   37.784267, -122.406579],
       [   1.      ,   37.784296, -122.406519],
       [   1.      ,   37.784464, -122.406181],
       [   1.      ,   37.784195, -122.40696 ],
       [   1.      ,   37.784221, -122.406652],
       [   1.      ,   37.784776, -122.406643],
       [   1.      ,   37.784527, -122.406296],
       [   1.      ,   37.78367 , -122.407313],
       [   1.      ,   37.783731, -122.407122],
       [   1.      ,   37.783976, -122.406906],
       [   1.      ,   37.784613, -122.406467],
       [   1.      ,   37.78398 , -122.407454],
       [   1.      ,   37.784714, -122.406476],
       [   1.      ,   37.78409 , -122.406835],
       [   1.      ,   37.784503, -122.406813],
       [   1.      ,   37.784112, -122.406949],
       [   1.      ,   37.784884, -122.406486],
       [   1.      ,   37.78461 , -122.406886],
       [   1.      ,   37.784466, -122.406961],
       [   1.      ,   37.78447 , -122.40676 ],
       [   1.      ,   37.78373 , -122.407061],
       [   1.      ,   37.783909, -122.407393],
       [   1.      ,   37.78381 , -122.407336],
       [   1.      ,   37.783864, -122.406836],
       [   1.      ,   37.784188, -122.407159],
       [   1.      ,   37.783827, -122.407024],
       [   1.      ,   37.784047, -122.407035],
       [   1.      ,   37.784397, -122.406148],
       [   1.      ,   37.784185, -122.406379],
       [   1.      ,   37.784396, -122.406726],
       [   2.      ,   37.784579, -122.406476],
       [   2.      ,   37.783744, -122.407323],
       [   2.      ,   37.784515, -122.406218],
       [   2.      ,   37.784024, -122.407272],
       [   2.      ,   37.784139, -122.407183],
       [   2.      ,   37.784341, -122.406785],
       [   2.      ,   37.784559, -122.40627 ],
       [   2.      ,   37.784136, -122.405805],
       [   2.      ,   37.784705, -122.406568],
       [   2.      ,   37.784142, -122.40742 ],
       [   2.      ,   37.784267, -122.406528],
       [   2.      ,   37.784046, -122.406884],
       [   2.      ,   37.784252, -122.406942],
       [   2.      ,   37.784387, -122.406732],
       [   2.      ,   37.783739, -122.407271],
       [   2.      ,   37.783745, -122.407149],
       [   2.      ,   37.784385, -122.406276],
       [   2.      ,   37.784195, -122.407081],
       [   2.      ,   37.784433, -122.40608 ],
       [   2.      ,   37.784031, -122.406181],
       [   2.      ,   37.783852, -122.405805],
       [   2.      ,   37.783931, -122.406086],
       [   2.      ,   37.784484, -122.406502],
       [   2.      ,   37.783724, -122.406893],
       [   2.      ,   37.784555, -122.406814],
       [   2.      ,   37.783832, -122.407021],
       [   2.      ,   37.783954, -122.407507],
       [   2.      ,   37.784185, -122.406432],
       [   2.      ,   37.783864, -122.406924],
       [   2.      ,   37.783946, -122.406796],
       [   2.      ,   37.784316, -122.40656 ],
       [   2.      ,   37.784172, -122.406733],
       [   2.      ,   37.784271, -122.406619],
       [   2.      ,   37.784286, -122.406001],
       [   3.      ,   37.784042, -122.406901],
       [   3.      ,   37.783629, -122.407154],
       [   3.      ,   37.783741, -122.406902],
       [   3.      ,   37.784628, -122.406187],
       [   3.      ,   37.78435 , -122.406064],
       [   3.      ,   37.784105, -122.406326],
       [   3.      ,   37.784615, -122.406862],
       [   3.      ,   37.784428, -122.406643],
       [   3.      ,   37.784447, -122.406809],
       [   3.      ,   37.783986, -122.406922],
       [   3.      ,   37.783839, -122.406836],
       [   3.      ,   37.783812, -122.406021],
       [   3.      ,   37.784133, -122.407419],
       [   3.      ,   37.783752, -122.407371],
       [   3.      ,   37.78429 , -122.406561],
       [   3.      ,   37.783737, -122.407253],
       [   3.      ,   37.78424 , -122.406455],
       [   3.      ,   37.784101, -122.406854],
       [   3.      ,   37.783871, -122.407073],
       [   3.      ,   37.784153, -122.405871],
       [   3.      ,   37.783745, -122.405601],
       [   3.      ,   37.784191, -122.407111],
       [   3.      ,   37.784267, -122.405933],
       [   3.      ,   37.784386, -122.406589],
       [   3.      ,   37.78454 , -122.406132],
       [   3.      ,   37.783912, -122.407474],
       [   3.      ,   37.784663, -122.406313],
       [   3.      ,   37.784135, -122.406406],
       [   3.      ,   37.783957, -122.406249],
       [   3.      ,   37.783814, -122.407399],
       [   3.      ,   37.784197, -122.40698 ],
       [   3.      ,   37.784701, -122.406758],
       [   3.      ,   37.78436 , -122.406786],
       [   4.      ,   37.78442 , -122.406832],
       [   4.      ,   37.784702, -122.406248],
       [   4.      ,   37.784206, -122.406528],
       [   4.      ,   37.784178, -122.405776],
       [   4.      ,   37.783859, -122.40635 ],
       [   4.      ,   37.784539, -122.406081],
       [   4.      ,   37.78382 , -122.407311],
       [   4.      ,   37.783802, -122.405736],
       [   5.      ,   37.784076, -122.407307],
       [   5.      ,   37.78389 , -122.405736],
       [   5.      ,   37.784204, -122.406574],
       [   6.      ,   37.78409 , -122.407309],
       [   7.      ,   37.784073, -122.407289],
       [   8.      ,   37.784087, -122.407307]])

In [179]:
#convert into matrix having mean= 0 and std dev= 1
from sklearn import preprocessing
scaler = preprocessing.StandardScaler()
X2 = scaler.fit_transform(X2)
X2

array([[-1.08827864e+00, -3.44149111e-01, -2.21927721e-01],
       [-1.08827864e+00,  1.40158609e+00,  1.04342435e+00],
       [-1.08827864e+00,  7.10205813e-01,  2.52317003e-01],
       [-1.08827864e+00, -1.45035756e+00, -1.40544110e+00],
       [-1.08827864e+00,  1.41887060e+00,  7.95809851e-01],
       [-1.08827864e+00,  1.18725820e+00,  1.43163353e+00],
       [-1.08827864e+00, -8.52313615e-01, -1.74118958e+00],
       [-1.08827864e+00,  8.86507784e-01,  1.01404636e+00],
       [-1.08827864e+00, -1.02166013e-01, -4.04490955e-01],
       [-1.08827864e+00,  2.13444919e+00,  4.32781810e-01],
       [-1.08827864e+00,  1.30824975e+00,  1.18821588e+00],
       [-1.08827864e+00,  1.65739679e+00,  5.92616288e-02],
       [-1.08827864e+00, -2.23157562e-01, -7.42337861e-01],
       [-1.08827864e+00, -1.09079816e-01,  7.49644435e-01],
       [-1.08827864e+00, -8.00460094e-01, -4.25475235e-01],
       [-1.08827864e+00,  7.62059334e-01, -3.69121068e-03],
       [-1.08827864e+00,  1.10774947e+00,  1.57642506e+00],
       [-1.08827864e+00, -4.13287138e-01, -3.73014536e-01],
       [-1.08827864e+00,  1.38430158e+00, -1.56876453e-01],
       [-1.08827864e+00, -1.42615925e+00, -9.52180659e-01],
       [-1.08827864e+00, -4.75511363e-01, -1.25855114e+00],
       [-1.08827864e+00, -1.02861559e+00, -1.43062224e+00],
       [-1.08827864e+00,  1.08704971e-01, -5.68168338e-01],
       [-1.08827864e+00, -8.21201502e-01, -1.28163385e+00],
       [-1.08827864e+00,  1.08700806e+00,  3.19466699e-01],
       [-1.08827864e+00, -1.46418516e+00, -7.61223712e-01],
       [-1.08827864e+00, -2.92295590e-01, -1.01093664e+00],
       [-1.08827864e+00,  3.50688069e-01,  1.46310995e+00],
       [-1.08827864e+00,  8.93421587e-01,  8.86396206e-02],
       [-1.08827864e+00,  5.61559053e-01, -1.37990602e-01],
       [-1.08827864e+00,  3.57601871e-01,  1.13995204e+00],
       [-1.08827864e+00,  4.47481308e-01,  1.07490077e+00],
       [-1.08827864e+00, -8.52313615e-01, -9.81558651e-01],
       [-1.08827864e+00, -1.24294347e+00, -4.90526503e-01],
       [-1.08827864e+00,  4.19826096e-01,  1.85761441e+00],
       [-1.08827864e+00, -1.04935699e+00,  1.93945310e+00],
       [-1.08827864e+00,  6.03083520e-02, -1.51665779e+00],
       [-1.08827864e+00,  1.08700806e+00,  6.46821464e-01],
       [-1.08827864e+00,  1.50183623e+00,  6.09049760e-01],
       [-1.08827864e+00, -2.33528266e-01, -5.09412354e-01],
       [-1.08827864e+00, -2.09329956e-01, -1.39914582e+00],
       [-1.08827864e+00, -5.30821786e-01, -4.82132791e-01],
       [-1.08827864e+00,  9.21076798e-01, -2.34518289e-01],
       [-1.08827864e+00,  7.75886940e-01,  1.80725214e+00],
       [-1.08827864e+00, -2.57726576e-01, -8.74538823e-01],
       [-1.08827864e+00, -1.15993619e-01,  1.64147633e+00],
       [-1.08827864e+00, -3.33778406e-01, -1.92585124e+00],
       [-1.08827864e+00, -1.38121953e+00, -5.80758906e-01],
       [-4.24108586e-01, -1.38467643e+00, -1.60059491e+00],
       [-4.24108586e-01,  1.46726722e+00,  7.87416139e-01],
       [-4.24108586e-01, -5.89589109e-01,  1.55753921e+00],
       [-4.24108586e-01, -3.99417883e-02, -3.31045976e-01],
       [-4.24108586e-01, -1.67847140e-01, -6.98270873e-01],
       [-4.24108586e-01,  9.07249192e-01,  5.54490633e-01],
       [-4.24108586e-01, -5.44649391e-01, -3.96097243e-01],
       [-4.24108586e-01,  2.64265534e-01,  2.69104427e-01],
       [-4.24108586e-01,  3.64515674e-01,  3.95010106e-01],
       [-4.24108586e-01,  9.45275108e-01,  1.10427876e+00],
       [-4.24108586e-01,  1.53686339e-02, -5.30396634e-01],
       [-4.24108586e-01,  1.05248070e-01,  1.15919184e-01],
       [-4.24108586e-01,  2.02382834e+00,  1.34805036e-01],
       [-4.24108586e-01,  1.16305990e+00,  8.62959546e-01],
       [-4.24108586e-01, -1.79950460e+00, -1.27114171e+00],
       [-4.24108586e-01, -1.58863361e+00, -8.70341967e-01],
       [-4.24108586e-01, -7.41692770e-01, -4.17081523e-01],
       [-4.24108586e-01,  1.46035341e+00,  5.04128361e-01],
       [-4.24108586e-01, -7.27865165e-01, -1.56702006e+00],
       [-4.24108586e-01,  1.80950046e+00,  4.85242509e-01],
       [-4.24108586e-01, -3.47606012e-01, -2.68093136e-01],
       [-4.24108586e-01,  1.08009426e+00, -2.21927721e-01],
       [-4.24108586e-01, -2.71554181e-01, -5.07313926e-01],
       [-4.24108586e-01,  2.39717369e+00,  4.64258229e-01],
       [-4.24108586e-01,  1.44998271e+00, -3.75112964e-01],
       [-4.24108586e-01,  9.52188910e-01, -5.32495062e-01],
       [-4.24108586e-01,  9.66016516e-01, -1.10711038e-01],
       [-4.24108586e-01, -1.59209051e+00, -7.42337861e-01],
       [-4.24108586e-01, -9.73305163e-01, -1.43901595e+00],
       [-4.24108586e-01, -1.31553840e+00, -1.31940556e+00],
       [-4.24108586e-01, -1.12886573e+00, -2.70191564e-01],
       [-4.24108586e-01, -8.82967582e-03, -9.47983803e-01],
       [-4.24108586e-01, -1.25677108e+00, -6.64696025e-01],
       [-4.24108586e-01, -4.96252772e-01, -6.87778733e-01],
       [-4.24108586e-01,  7.13662715e-01,  1.17352689e+00],
       [-4.24108586e-01, -1.92003800e-02,  6.88790024e-01],
       [-4.24108586e-01,  7.10205813e-01, -3.93644864e-02],
       [ 2.40061464e-01,  1.34281877e+00,  4.85242509e-01],
       [ 2.40061464e-01, -1.54369389e+00, -1.29212599e+00],
       [ 2.40061464e-01,  1.12157708e+00,  1.02663693e+00],
       [ 2.40061464e-01, -5.75761504e-01, -1.18510616e+00],
       [ 2.40061464e-01, -1.78217844e-01, -9.98346074e-01],
       [ 2.40061464e-01,  5.20076237e-01, -1.63171737e-01],
       [ 2.40061464e-01,  1.27368074e+00,  9.17518674e-01],
       [ 2.40061464e-01, -1.88588548e-01,  1.89328769e+00],
       [ 2.40061464e-01,  1.77838834e+00,  2.92187135e-01],
       [ 2.40061464e-01, -1.67847140e-01, -1.49567351e+00],
       [ 2.40061464e-01,  2.64265534e-01,  3.76124254e-01],
       [ 2.40061464e-01, -4.99709673e-01, -3.70916108e-01],
       [ 2.40061464e-01,  2.12412013e-01, -4.92624931e-01],
       [ 2.40061464e-01,  6.79093701e-01, -5.19550543e-02],
       [ 2.40061464e-01, -1.56097840e+00, -1.18300774e+00],
       [ 2.40061464e-01, -1.54023699e+00, -9.26999523e-01],
       [ 2.40061464e-01,  6.72179898e-01,  9.04928106e-01],
       [ 2.40061464e-01,  1.53686339e-02, -7.84306420e-01],
       [ 2.40061464e-01,  8.38111165e-01,  1.31621999e+00],
       [ 2.40061464e-01, -5.51563194e-01,  1.10427876e+00],
       [ 2.40061464e-01, -1.17034854e+00,  1.89328769e+00],
       [ 2.40061464e-01, -8.97253333e-01,  1.30362942e+00],
       [ 2.40061464e-01,  1.01441314e+00,  4.30683382e-01],
       [ 2.40061464e-01, -1.61283192e+00, -3.89801959e-01],
       [ 2.40061464e-01,  1.25985313e+00, -2.24026149e-01],
       [ 2.40061464e-01, -1.23948657e+00, -6.58400741e-01],
       [ 2.40061464e-01, -8.17744601e-01, -1.67823674e+00],
       [ 2.40061464e-01, -1.92003800e-02,  5.77573341e-01],
       [ 2.40061464e-01, -1.12886573e+00, -4.54853227e-01],
       [ 2.40061464e-01, -8.45399812e-01, -1.86254445e-01],
       [ 2.40061464e-01,  4.33653702e-01,  3.08974559e-01],
       [ 2.40061464e-01, -6.41400981e-02, -5.40534823e-02],
       [ 2.40061464e-01,  2.78093139e-01,  1.85167308e-01],
       [ 2.40061464e-01,  3.29946660e-01,  1.48199580e+00],
       [ 9.04231513e-01, -5.13537279e-01, -4.06589383e-01],
       [ 9.04231513e-01, -1.94123755e+00, -9.37491663e-01],
       [ 9.04231513e-01, -1.55406460e+00, -4.08687811e-01],
       [ 9.04231513e-01,  1.51220694e+00,  1.09168820e+00],
       [ 9.04231513e-01,  5.51188349e-01,  1.34979484e+00],
       [ 9.04231513e-01, -2.95752491e-01,  8.00006707e-01],
       [ 9.04231513e-01,  1.46726722e+00, -3.24750692e-01],
       [ 9.04231513e-01,  8.20826658e-01,  1.34805036e-01],
       [ 9.04231513e-01,  8.86507784e-01, -2.13534009e-01],
       [ 9.04231513e-01, -7.07123756e-01, -4.50656371e-01],
       [ 9.04231513e-01, -1.21528826e+00, -2.70191564e-01],
       [ 9.04231513e-01, -1.30862460e+00,  1.44002724e+00],
       [ 9.04231513e-01, -1.98959252e-01, -1.49357508e+00],
       [ 9.04231513e-01, -1.51603868e+00, -1.39285054e+00],
       [ 9.04231513e-01,  3.43774266e-01,  3.06876131e-01],
       [ 9.04231513e-01, -1.56789220e+00, -1.14523603e+00],
       [ 9.04231513e-01,  1.70929196e-01,  5.29309497e-01],
       [ 9.04231513e-01, -3.09580097e-01, -3.07963268e-01],
       [ 9.04231513e-01, -1.10466742e+00, -7.67518996e-01],
       [ 9.04231513e-01, -1.29821224e-01,  1.75479144e+00],
       [ 9.04231513e-01, -1.54023699e+00,  2.32136699e+00],
       [ 9.04231513e-01,  1.54102834e-03, -8.47259260e-01],
       [ 9.04231513e-01,  2.64265534e-01,  1.62468890e+00],
       [ 9.04231513e-01,  6.75636799e-01,  2.48120147e-01],
       [ 9.04231513e-01,  1.20799961e+00,  1.20710174e+00],
       [ 9.04231513e-01, -9.62934459e-01, -1.60898862e+00],
       [ 9.04231513e-01,  1.63319848e+00,  8.27286270e-01],
       [ 9.04231513e-01, -1.92045449e-01,  6.32132468e-01],
       [ 9.04231513e-01, -8.07373897e-01,  9.61585661e-01],
       [ 9.04231513e-01, -1.30171080e+00, -1.45160652e+00],
       [ 9.04231513e-01,  2.22824367e-02, -5.72365194e-01],
       [ 9.04231513e-01,  1.76456074e+00, -1.06514182e-01],
       [ 9.04231513e-01,  5.85757363e-01, -1.65270165e-01],
       [ 1.56840156e+00,  7.93171447e-01, -2.61797853e-01],
       [ 1.56840156e+00,  1.76801764e+00,  9.63684089e-01],
       [ 1.56840156e+00,  5.33945492e-02,  3.76124254e-01],
       [ 1.56840156e+00, -4.33986897e-02,  1.95414210e+00],
       [ 1.56840156e+00, -1.14615023e+00,  7.49644435e-01],
       [ 1.56840156e+00,  1.20454271e+00,  1.31412156e+00],
       [ 1.56840156e+00, -1.28096939e+00, -1.26694486e+00],
       [ 1.56840156e+00, -1.34319361e+00,  2.03807922e+00],
       [ 2.23257161e+00, -3.96002631e-01, -1.25855114e+00],
       [ 2.23257161e+00, -1.03898629e+00,  2.03807922e+00],
       [ 2.23257161e+00,  4.64807464e-02,  2.79596567e-01],
       [ 2.89674166e+00, -3.47606012e-01, -1.26274800e+00],
       [ 3.56091171e+00, -4.06373336e-01, -1.22077944e+00],
       [ 4.22508176e+00, -3.57976716e-01, -1.25855114e+00]])

In [180]:
y2 = storemap['Store_Category'].as_matrix().astype(object)
y2

array([u'Qsr Restaurants', u'Qsr Restaurants', u'Apparel And Accessories',
       u'Office Supply Stores', u'Qsr Restaurants', u'Qsr Restaurants',
       u'Apparel And Accessories', u'Qsr Restaurants', u'Misc.',
       u'Shoe Stores', u'Qsr Restaurants', u'Qsr Restaurants',
       u'Apparel And Accessories', u'Casual Restaurants',
       u'Apparel And Accessories', u'Qsr Restaurants', u'Qsr Restaurants',
       u'Apparel And Accessories', u'Qsr Restaurants', u'Qsr Restaurants',
       u'Furniture And Decor', u'Sports Stores', u'Toy Stores',
       u'Qsr Restaurants', u'Qsr Restaurants', u'Qsr Restaurants',
       u'Shoe Stores', u'Qsr Restaurants', u'Qsr Restaurants',
       u'Toy Stores', u'Qsr Restaurants', u'Qsr Restaurants',
       u'Qsr Restaurants', u'Qsr Restaurants', u'Qsr Restaurants',
       u'Department Stores', u'Sports Stores', u'Qsr Restaurants',
       u'Qsr Restaurants', u'Qsr Restaurants', u'Misc.',
       u'Qsr Restaurants', u'Furniture And Decor', u'Qsr Restaurants',
       u'Sports Stores', u'Qsr Restaurants', u'Qsr Restaurants',
       u'Qsr Restaurants', u'Specialty Store', u'Apparel And Accessories',
       u'Department Stores', u'Misc.', u'Furniture And Decor', u'Misc.',
       u'Apparel And Accessories', u'Furniture And Decor',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel and Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel and Accessories',
       u'Apparel And Accessories', u'Misc.', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Furniture And Decor', u'Misc.',
       u'Apparel And Accessories', u'Apparel And Accessories', u'Misc.',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Furniture And Decor', u'Apparel And Accessories', u'Misc.',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Qsr Restaurants', u'Furniture And Decor', u'Misc.',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel and Accessories', u'Apparel And Accessories',
       u'Furniture And Decor', u'Furniture And Decor',
       u'Apparel And Accessories', u'Qsr Restaurants',
       u'Apparel And Accessories', u'Furniture And Decor',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Shoe Stores', u'Sports Stores', u'Apparel And Accessories',
       u'Misc.', u'Furniture And Decor', u'Apparel And Accessories',
       u'Cellular Phone Stores', u'Department Stores',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Department Stores', u'Sports Stores', u'Apparel and Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories', u'Misc.',
       u'Apparel And Accessories', u'Electronics Stores',
       u'Apparel and Accessories', u'Apparel And Accessories',
       u'Furniture And Decor', u'Shoe Stores', u'Qsr Restaurants',
       u'Apparel And Accessories', u'Shoe Stores',
       u'Apparel And Accessories', u'Office Supply Stores',
       u'Apparel and Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Qsr Restaurants', u'Apparel And Accessories', u'Shoe Stores',
       u'Sports Stores', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Furniture And Decor', u'Misc.',
       u'Furniture And Decor', u'Shoe Stores', u'Apparel and Accessories',
       u'Electronics Stores', u'Toy Stores', u'Department Stores',
       u'Apparel And Accessories', u'Shoe Stores', u'Furniture And Decor',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Furniture And Decor',
       u'Apparel And Accessories', u'Qsr Restaurants', u'Shoe Stores',
       u'Furniture And Decor', u'Apparel And Accessories',
       u'Qsr Restaurants', u'Furniture And Decor', u'Qsr Restaurants',
       u'Specialty Store', u'Misc.', u'Electronics Stores',
       u'Department Stores', u'Department Stores', u'Department Stores',
       u'Misc.', u'Misc.', u'Department Stores', u'Department Stores',
       u'Department Stores'], dtype=object)

In [181]:
def stratified_cv(X, y, clf_class, shuffle=True, n_folds=2, **kwargs):
    stratified_k_fold = cross_validation.StratifiedKFold(y, n_folds=n_folds, shuffle=shuffle)
    y_pred = y.copy()
    for ii, jj in stratified_k_fold:
        X_train, X_test = X[ii], X[jj]
        y_train = y[ii]
        clf = clf_class(**kwargs)
        clf.fit(X_train,y_train)
        y_pred[jj] = clf.predict(X_test)
    return y_pred

In [182]:
print('Passive Aggressive Classifier: {:.2f}'.format(metrics.accuracy_score(y2, stratified_cv(X2, y2, linear_model.PassiveAggressiveClassifier))))
print('Gradient Boosting Classifier:  {:.2f}'.format(metrics.accuracy_score(y2, stratified_cv(X2, y2, ensemble.GradientBoostingClassifier))))
print('Support vector machine(SVM):   {:.2f}'.format(metrics.accuracy_score(y2, stratified_cv(X2, y2, svm.SVC))))
print('Random Forest Classifier:      {:.2f}'.format(metrics.accuracy_score(y2, stratified_cv(X2, y2, ensemble.RandomForestClassifier))))
print('K Nearest Neighbor Classifier: {:.2f}'.format(metrics.accuracy_score(y2, stratified_cv(X2, y2, neighbors.KNeighborsClassifier))))
print('Logistic Regression:           {:.2f}'.format(metrics.accuracy_score(y2, stratified_cv(X2, y2, linear_model.LogisticRegression))))

Passive Aggressive Classifier: 0.30
Gradient Boosting Classifier:  0.36
Support vector machine(SVM):   0.48
Random Forest Classifier:      0.35
K Nearest Neighbor Classifier: 0.39
Logistic Regression:           0.28

In [198]:
#SVM TRAINING AND FITTING:
from sklearn.svm import SVC

clf2 = svm.SVC(kernel='rbf', C=100, gamma=10)
clf2.fit(X2, y2)


# Training data features, skip the first column 'Survived'
train_features = X2

# 'Survived' column values
train_target = y2

# Fit the model to our training data
clf2 = clf2.fit(train_features, train_target)
score = clf2.score(train_features, train_target)
"Mean accuracy of SVM: {0}".format(score)

'Mean accuracy of SVM: 1.0'

In [195]:
pinginfo.head()

    Shopper_ID  Floor_Index   latitude   longitude Store_Name
0  Shopper_556            4  37.661463 -122.298673    TAP 415
1  Shopper_556            1  37.784062 -122.406943    Kiehl's
2  Shopper_556            4  37.784361 -122.406710    TAP 415
3  Shopper_360            0  37.784341 -122.406891    Kiehl's
4  Shopper_360            2  37.784017 -122.407307  Cotton On

In [199]:
X_test2 = pinginfo.drop(['Shopper_ID', 'Store_Name'], axis=1).as_matrix().astype(np.float)
X_test2

array([[   4.        ,   37.66146302, -122.2986728 ],
       [   1.        ,   37.78406211, -122.4069432 ],
       [   4.        ,   37.78436125, -122.4067095 ],
       ...,
       [   2.        ,   36.0179502 , -116.704627  ],
       [   1.        ,   37.78404745, -122.4069997 ],
       [   0.        ,   37.78407819, -122.4070869 ]])

In [200]:
scaler = preprocessing.StandardScaler()
test_data2 = scaler.fit_transform(X_test2)
test_data2

array([[ 1.83464372,  0.36209925, -0.40275272],
       [-0.32798594,  0.42248019, -0.41922354],
       [ 1.83464372,  0.42262752, -0.41918799],
       ...,
       [ 0.39289061, -0.44734271,  0.44825139],
       [-0.32798594,  0.42247297, -0.41923214],
       [-1.04886249,  0.42248811, -0.4192454 ]])

In [201]:
pred_y2 = clf2.predict(test_data2)

In [202]:
pinginfo['Store_Category_visited'] = pred_y2
pinginfo

,Shopper_ID,Floor_Index,latitude,longitude,Store_Name,Store_Category_visited
0,Shopper_556,4,37.661463,-122.298673,TAP 415,Apparel And Accessories
1,Shopper_556,1,37.784062,-122.406943,Kiehl's,Apparel And Accessories
2,Shopper_556,4,37.784361,-122.406710,TAP 415,Apparel And Accessories
3,Shopper_360,0,37.784341,-122.406891,Kiehl's,Toy Stores
4,Shopper_360,2,37.784017,-122.407307,Cotton On,Apparel And Accessories
5,Shopper_420,4,37.661624,-122.298459,TAP 415,Apparel And Accessories
6,Shopper_420,1,37.783856,-122.407092,Kiehl's,Apparel And Accessories
7,Shopper_245,2,37.783970,-122.407194,Cotton On,Apparel And Accessories
8,Shopper_334,2,37.783828,-122.406986,Cotton On,Apparel And Accessories
9,Shopper_205,1,37.784219,-122.406896,Kiehl's,Apparel And Accessories
10,Shopper_205,0,37.784638,-122.406411,Kiehl's,Toy Stores
11,Shopper_530,1,35.085149,-113.663734,49ers Team Store,Apparel And Accessories
12,Shopper_530,0,36.541271,-118.435462,Jamba Juice,Qsr Restaurants
13,Shopper_359,0,37.783961,-122.407034,Kiehl's,Toy Stores
14,Shopper_189,0,35.239976,-114.220990,Bloomingdale's,Apparel And Accessories
15,Shopper_189,0,37.784049,-122.407055,Kiehl's,Toy Stores
16,Shopper_189,0,37.784084,-122.407044,Kiehl's,Toy Stores
17,Shopper_481,2,35.265054,-114.246672,H&M Man,Apparel And Accessories
18,Shopper_155,4,37.784287,-122.406954,TAP 415,Apparel And Accessories
19,Shopper_155,1,36.980523,-119.811229,Kiehl's,Apparel And Accessories
20,Shopper_155,4,37.759561,-122.385293,TAP 415,Apparel And Accessories
21,Shopper_287,0,37.656648,-122.006913,Kiehl's,Toy Stores
22,Shopper_536,2,34.031987,-110.253652,Bloomingdale's,Apparel And Accessories
23,Shopper_344,2,37.784028,-122.407106,Cotton On,Apparel And Accessories
24,Shopper_41,2,33.504061,-108.734063,Bloomingdale's,Apparel And Accessories
25,Shopper_41,3,37.783814,-122.407127,Solstice,Apparel And Accessories
26,Shopper_122,4,36.066776,-116.842850,M.Y. China,Apparel And Accessories
27,Shopper_51,0,37.720868,-122.343518,Kiehl's,Toy Stores
28,Shopper_51,1,35.265134,-114.246611,49ers Team Store,Apparel And Accessories
29,Shopper_68,1,37.783840,-122.407236,Kiehl's,Apparel And Accessories
...,...,...,...,...,...,...
107605,Shopper_454,1,37.783982,-122.406909,Kiehl's,Apparel And Accessories
107606,Shopper_278,3,30.227258,-97.925617,Bloomingdale's,Apparel And Accessories
107607,Shopper_318,2,37.784039,-122.406977,Cotton On,Apparel And Accessories
107608,Shopper_440,0,37.784117,-122.407263,Kiehl's,Toy Stores
107609,Shopper_363,0,37.784069,-122.407386,Kiehl's,Toy Stores
107610,Shopper_339,0,37.783989,-122.407159,Kiehl's,Toy Stores
107611,Shopper_47,0,31.487016,-102.005697,Bloomingdale's,Apparel And Accessories
107612,Shopper_320,2,37.781113,-122.404167,Kiehl's,Apparel And Accessories
107613,Shopper_4,2,37.784046,-122.407011,Cotton On,Apparel And Accessories
107614,Shopper_398,2,33.061211,-107.106029,Bloomingdale's,Apparel And Accessories
107615,Shopper_154,1,37.784085,-122.406878,Kiehl's,Apparel And Accessories
107616,Shopper_459,0,37.784052,-122.407107,Kiehl's,Toy Stores
107617,Shopper_459,0,37.784471,-122.406800,Kiehl's,Toy Stores
107618,Shopper_419,2,37.743028,-122.371079,Kiehl's,Apparel And Accessories
107619,Shopper_319,3,34.320329,-111.206542,abercrombie kids,Apparel And Accessories
107620,Shopper_319,0,37.784294,-122.406786,Kiehl's,Toy Stores
107621,Shopper_319,2,34.315878,-111.249350,Bloomingdale's,Apparel And Accessories
107622,Shopper_468,2,37.783898,-122.407144,Cotton On,Apparel And Accessories
107623,Shopper_244,3,37.781999,-122.405348,Solstice,Apparel And Accessories
107624,Shopper_373,3,37.783965,-122.407176,Solstice,Apparel And Accessories
107625,Shopper_376,1,37.784045,-122.407060,Kiehl's,Apparel And Accessories
107626,Shopper_100,0,35.219027,-114.115492,Bloomingdale's,Apparel And Accessories
107627,Shopper_100,0,37.784057,-122.407213,Kiehl's,Toy Stores
107628,Shopper_28,2,37.783934,-122.407144,Cotton On,Apparel And Accessories
107629,Shopper_76,1,37.783984,-122.407237,Kiehl's,Apparel And Accessories
107630,Shopper_317,4,28.338261,-91.805123,Bloomingdale's,Apparel And Accessories
107631,Shopper_295,4,37.784115,-122.406981,TAP 415,Apparel And Accessories
107632,Shopper_460,2,36.017950,-116.704627,Microsoft,Apparel And Accessories
107633,Shopper_190,1,37.784047,-122.407000,Kiehl's,Apparel And Accessories
107634,Shopper_53,0,37.784078,-122.407087,Kiehl's,Toy Stores

In [203]:
visiting_info2 = pinginfo.groupby(['Shopper_ID', 'Store_Category_visited']).describe()

In [206]:
visiting_info2.drop(['latitude', 'longitude'], axis=1, inplace=True)
visiting_info2.head()

                                   Floor_Index                                \
                                         count      mean       std  min  25%
Shopper_ID Store_Category_visited
Shopper_1  Apparel And Accessories       159.0  1.767296  1.238593  0.0  1.0
           Toy Stores                     30.0  0.000000  0.000000  0.0  0.0
Shopper_10 Apparel And Accessories       153.0  2.875817  1.465930  0.0  1.0
           Misc.                           5.0  1.000000  0.000000  1.0  1.0
           Qsr Restaurants                 1.0  0.000000       NaN  0.0  0.0


                                    50%  75%  max
Shopper_ID Store_Category_visited
Shopper_1  Apparel And Accessories  2.0  3.0  4.0
           Toy Stores               0.0  0.0  0.0
Shopper_10 Apparel And Accessories  4.0  4.0  4.0
           Misc.                    1.0  1.0  1.0
           Qsr Restaurants          0.0  0.0  0.0

In [207]:
#visiting_info2.to_csv(r"C:\Users\welcome\Desktop\visitinginfo2.csv")

In [208]:
visitinginfo2 = pd.read_csv(r"C:\Users\welcome\Desktop\visitinginfo2.csv")
visitinginfo2.head()

,Shopper_ID,Store_Category_visited,count,mean,std,min,25%,50%,75%,max
0,Shopper_1,Apparel And Accessories,159,1.767296,1.238593,0,1.0,2.0,3.0,4
1,Shopper_1,Toy Stores,30,0.000000,0.000000,0,0.0,0.0,0.0,0
2,Shopper_10,Apparel And Accessories,153,2.875817,1.465930,0,1.0,4.0,4.0,4
3,Shopper_10,Misc.,5,1.000000,0.000000,1,1.0,1.0,1.0,1
4,Shopper_10,Qsr Restaurants,1,0.000000,NaN,0,0.0,0.0,0.0,0

In [209]:
from scipy import stats
df_freq_category = pinginfo.groupby(by='Shopper_ID').Store_Category_visited.apply(stats.mode)

In [211]:
df_freq_category= df_freq_category.to_frame()
df_freq_category.iloc[1,:]

Store_Category_visited    ([Apparel And Accessories], [153])
Name: Shopper_10, dtype: object

In [212]:
mostvisitedcategorylist= []
for category in df_freq_category['Store_Category_visited']:
    mostvisitedcategorylist.append(category[0][0])
    
mostvisitedcategory_array= np.array(mostvisitedcategorylist)
mostvisitedcategory_array

array([u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Toy Stores', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Toy Stores', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Toy Stores', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Toy Stores',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Toy Stores', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Toy Stores', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Toy Stores', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Toy Stores', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Toy Stores', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Toy Stores',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Toy Stores',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Toy Stores', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Toy Stores', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Toy Stores', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Toy Stores', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Toy Stores', u'Toy Stores',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Toy Stores', u'Toy Stores',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Toy Stores',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Toy Stores', u'Apparel And Accessories', u'Toy Stores',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Toy Stores',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Toy Stores', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Toy Stores', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Toy Stores',
       u'Apparel And Accessories', u'Toy Stores',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Toy Stores', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Toy Stores',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Toy Stores',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Toy Stores',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Toy Stores', u'Apparel And Accessories', u'Toy Stores',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Toy Stores',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Toy Stores',
       u'Apparel And Accessories', u'Toy Stores',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Toy Stores', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Toy Stores', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Toy Stores',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Toy Stores', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Toy Stores',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Toy Stores',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Toy Stores',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Toy Stores', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Toy Stores',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Toy Stores',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories', u'Apparel And Accessories',
       u'Apparel And Accessories'], dtype='<U23')

In [213]:
mostvisitedcategory_array.astype(object)
df_freq_category['New_Store_Category_visited']= mostvisitedcategory_array
df_freq_category.head()

                         Store_Category_visited New_Store_Category_visited
Shopper_ID
Shopper_1    ([Apparel And Accessories], [159])    Apparel And Accessories
Shopper_10   ([Apparel And Accessories], [153])    Apparel And Accessories
Shopper_100  ([Apparel And Accessories], [118])    Apparel And Accessories
Shopper_101  ([Apparel And Accessories], [143])    Apparel And Accessories
Shopper_102  ([Apparel And Accessories], [174])    Apparel And Accessories

In [214]:
df_freq_category.to_csv(r"C:\Users\welcome\Desktop\exl__svm2ndpart2.csv")

In [215]:
df_freq

                           Store_Name       New_Store
Shopper_ID
Shopper_1    ([Bloomingdale's], [67])  Bloomingdale's
Shopper_10          ([Kiehl's], [76])         Kiehl's
Shopper_100         ([Kiehl's], [99])         Kiehl's
Shopper_101         ([Kiehl's], [99])         Kiehl's
Shopper_102        ([TAP 415], [125])         TAP 415
Shopper_103         ([Kiehl's], [72])         Kiehl's
Shopper_104        ([Kiehl's], [118])         Kiehl's
Shopper_105        ([Kiehl's], [110])         Kiehl's
Shopper_106        ([Kiehl's], [123])         Kiehl's
Shopper_107         ([Kiehl's], [96])         Kiehl's
Shopper_108        ([Kiehl's], [166])         Kiehl's
Shopper_109         ([Kiehl's], [72])         Kiehl's
Shopper_11         ([Kiehl's], [107])         Kiehl's
Shopper_110         ([Kiehl's], [72])         Kiehl's
Shopper_111        ([Kiehl's], [103])         Kiehl's
Shopper_112        ([Kiehl's], [105])         Kiehl's
Shopper_113        ([Kiehl's], [137])         Kiehl's
Shopper_114         ([TAP 415], [89])         TAP 415
Shopper_115         ([Kiehl's], [56])         Kiehl's
Shopper_116        ([TAP 415], [166])         TAP 415
Shopper_117        ([Kiehl's], [154])         Kiehl's
Shopper_118        ([Kiehl's], [106])         Kiehl's
Shopper_119        ([Kiehl's], [144])         Kiehl's
Shopper_12          ([Kiehl's], [72])         Kiehl's
Shopper_120        ([Kiehl's], [111])         Kiehl's
Shopper_121         ([Kiehl's], [80])         Kiehl's
Shopper_122         ([Kiehl's], [72])         Kiehl's
Shopper_123        ([Kiehl's], [139])         Kiehl's
Shopper_124        ([Kiehl's], [126])         Kiehl's
Shopper_125         ([Kiehl's], [70])         Kiehl's
...                               ...             ...
Shopper_72          ([Kiehl's], [84])         Kiehl's
Shopper_73          ([Kiehl's], [85])         Kiehl's
Shopper_74         ([Kiehl's], [120])         Kiehl's
Shopper_75         ([Kiehl's], [109])         Kiehl's
Shopper_76         ([Kiehl's], [181])         Kiehl's
Shopper_77          ([Kiehl's], [64])         Kiehl's
Shopper_78          ([Kiehl's], [61])         Kiehl's
Shopper_79          ([Kiehl's], [73])         Kiehl's
Shopper_8           ([Kiehl's], [95])         Kiehl's
Shopper_80          ([Kiehl's], [90])         Kiehl's
Shopper_81          ([Kiehl's], [96])         Kiehl's
Shopper_82          ([Kiehl's], [73])         Kiehl's
Shopper_83         ([Kiehl's], [105])         Kiehl's
Shopper_84          ([TAP 415], [85])         TAP 415
Shopper_85         ([Kiehl's], [141])         Kiehl's
Shopper_86          ([Kiehl's], [76])         Kiehl's
Shopper_87          ([Kiehl's], [62])         Kiehl's
Shopper_88          ([Kiehl's], [77])         Kiehl's
Shopper_89         ([Kiehl's], [138])         Kiehl's
Shopper_9          ([Kiehl's], [119])         Kiehl's
Shopper_90         ([Kiehl's], [106])         Kiehl's
Shopper_91         ([Kiehl's], [128])         Kiehl's
Shopper_92          ([Kiehl's], [98])         Kiehl's
Shopper_93          ([Kiehl's], [52])         Kiehl's
Shopper_94          ([Kiehl's], [93])         Kiehl's
Shopper_95         ([Kiehl's], [121])         Kiehl's
Shopper_96          ([Kiehl's], [91])         Kiehl's
Shopper_97   ([Bloomingdale's], [59])  Bloomingdale's
Shopper_98         ([Kiehl's], [115])         Kiehl's
Shopper_99          ([Kiehl's], [92])         Kiehl's

[567 rows x 2 columns]

In [217]:
frames = [df_freq, df_freq_category]
result = pd.concat(frames, axis=1)

In [218]:
result.to_csv(r"C:\Users\welcome\Desktop\exl__final22.csv")